### ISSUE TITLE
Unexpected Spark Job Server shutdown

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#1017]
For some reason, Spark Job Server shut itself down (and the geoprocessing context), but was still responding to HTTP requests:

```
2015-11-12 15:46:49,114 [JobServer-akka.actor.default-dispatcher-6] INFO  akka.event.slf4j.Slf4jLogger -  Slf4jLogger started
2015-11-12 15:46:49,283 [main] INFO  spark.jobserver.io.JobFileDAO -  rootDir is /opt/spark-jobserver/filedao/data
2015-11-12 15:46:49,916 [JobServer-akka.actor.default-dispatcher-6] INFO  spark.jobserver.JarManager -  Starting actor spark.jobserver.JarManager
2015-11-12 15:46:49,919 [JobServer-akka.actor.default-dispatcher-3] INFO  spark.jobserver.LocalContextSupervisorActor -  Starting actor spark.jobserver.LocalContextSupervisorActor
2015-11-12 15:46:50,070 [JobServer-akka.actor.default-dispatcher-4] INFO  spark.jobserver.JobInfoActor -  Starting actor spark.jobserver.JobInfoActor
2015-11-12 15:46:51,417 [JobServer-akka.actor.default-dispatcher-6] INFO  spark.jobserver.JobResultActor -  Starting actor spark.jobserver.JobResultActor
2015-11-12 15:46:51,446 [JobServer-akka.actor.default-dispatcher-3] INFO  spark.jobserver.LocalContextSupervisorActor -  Creating a SparkContext named geoprocessing
2015-11-12 15:46:51,460 [JobServer-akka.actor.default-dispatcher-6] INFO  spark.jobserver.JobManagerActor -  Starting actor spark.jobserver.JobManagerActor
2015-11-12 15:46:51,478 [JobServer-akka.actor.default-dispatcher-4] INFO  spark.jobserver.JobStatusActor -  Starting actor spark.jobserver.JobStatusActor
2015-11-12 15:46:51,486 [JobServer-akka.actor.default-dispatcher-4] INFO  spark.jobserver.JobResultActor -  Starting actor spark.jobserver.JobResultActor
2015-11-12 15:46:52,339 [JobServer-akka.actor.default-dispatcher-6] INFO  spark.jobserver.context.DefaultSparkContextFactory$$anon$1 -  Running Spark version 1.3.1
2015-11-12 15:46:55,506 [main] INFO  spark.jobserver.WebApi -  Starting browser web service...
2015-11-12 15:46:57,924 [JobServer-akka.actor.default-dispatcher-6] WARN  org.apache.hadoop.util.NativeCodeLoader -  Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2015-11-12 15:46:59,322 [JobServer-akka.actor.default-dispatcher-6] INFO  org.apache.spark.SecurityManager -  Changing view acls to: root
2015-11-12 15:46:59,323 [JobServer-akka.actor.default-dispatcher-6] INFO  org.apache.spark.SecurityManager -  Changing modify acls to: root
2015-11-12 15:46:59,326 [JobServer-akka.actor.default-dispatcher-6] INFO  org.apache.spark.SecurityManager -  SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(root); users with modify permissions: Set(root)
2015-11-12 15:47:00,033 [sparkDriver-akka.actor.default-dispatcher-4] INFO  akka.event.slf4j.Slf4jLogger -  Slf4jLogger started
2015-11-12 15:47:00,483 [sparkDriver-akka.actor.default-dispatcher-8] INFO  Remoting -  Starting remoting
2015-11-12 15:47:01,320 [sparkDriver-akka.actor.default-dispatcher-8] INFO  Remoting -  Remoting started; listening on addresses :[akka.tcp://sparkDriver@7898949b0e5a:49993]
2015-11-12 15:47:01,363 [JobServer-akka.actor.default-dispatcher-6] INFO  org.apache.spark.util.Utils -  Successfully started service 'sparkDriver' on port 49993.
2015-11-12 15:47:01,666 [JobServer-akka.actor.default-dispatcher-6] INFO  org.apache.spark.SparkEnv -  Registering MapOutputTracker
2015-11-12 15:47:01,733 [JobServer-akka.actor.default-dispatcher-6] INFO  org.apache.spark.SparkEnv -  Registering BlockManagerMaster
2015-11-12 15:47:01,838 [JobServer-akka.actor.default-dispatcher-6] INFO  org.apache.spark.storage.DiskBlockManager -  Created local directory at /tmp/spark-19ad915e-8f61-48e7-a15b-69660d422874/blockmgr-fad8ec9b-9c33-4e72-b253-2ef95efdf094
2015-11-12 15:47:01,859 [JobServer-akka.actor.default-dispatcher-6] INFO  org.apache.spark.storage.MemoryStore -  MemoryStore started with capacity 548.5 MB
2015-11-12 15:47:02,152 [JobServer-akka.actor.default-dispatcher-6] INFO  org.apache.spark.HttpFileServer -  HTTP File server directory is /tmp/spark-e8a0b5a7-6987-427d-af41-a11d7bcd83f1/httpd-9346a427-fa5d-484e-a1ae-755876f64348
2015-11-12 15:47:02,318 [JobServer-akka.actor.default-dispatcher-6] INFO  org.apache.spark.HttpServer -  Starting HTTP Server
2015-11-12 15:47:02,597 [JobServer-akka.actor.default-dispatcher-6] INFO  org.spark-project.jetty.server.Server -  jetty-8.y.z-SNAPSHOT
2015-11-12 15:47:02,669 [JobServer-akka.actor.default-dispatcher-6] INFO  org.spark-project.jetty.server.AbstractConnector -  Started SocketConnector@0.0.0.0:55352
2015-11-12 15:47:02,670 [JobServer-akka.actor.default-dispatcher-6] INFO  org.apache.spark.util.Utils -  Successfully started service 'HTTP file server' on port 55352.
2015-11-12 15:47:02,853 [JobServer-akka.actor.default-dispatcher-6] INFO  org.apache.spark.SparkEnv -  Registering OutputCommitCoordinator
2015-11-12 15:47:03,448 [JobServer-akka.actor.default-dispatcher-6] INFO  org.spark-project.jetty.server.Server -  jetty-8.y.z-SNAPSHOT
2015-11-12 15:47:03,498 [JobServer-akka.actor.default-dispatcher-6] INFO  org.spark-project.jetty.server.AbstractConnector -  Started SelectChannelConnector@0.0.0.0:45661
2015-11-12 15:47:03,499 [JobServer-akka.actor.default-dispatcher-6] INFO  org.apache.spark.util.Utils -  Successfully started service 'SparkUI' on port 45661.
2015-11-12 15:47:03,501 [JobServer-akka.actor.default-dispatcher-6] INFO  org.apache.spark.ui.SparkUI -  Started SparkUI at http://7898949b0e5a:45661
2015-11-12 15:47:03,632 [JobServer-akka.actor.default-dispatcher-2] INFO  spray.can.server.HttpListener -  Bound to /0.0.0.0:8090
2015-11-12 15:47:03,635 [JobServer-akka.actor.default-dispatcher-2] INFO  akka.actor.DeadLetterActorRef -  Message [akka.io.Tcp$Bound] from Actor[akka://JobServer/user/IO-HTTP/listener-0#1295175808] to Actor[akka://JobServer/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
2015-11-12 15:47:05,087 [JobServer-akka.actor.default-dispatcher-6] INFO  spark.jobserver.context.DefaultSparkContextFactory$$anon$1 -  Added JAR file:/opt/spark-jobserver/spark-job-server.jar at http://172.17.0.1:55352/jars/spark-job-server.jar with timestamp 1447343225086
2015-11-12 15:47:05,253 [sparkDriver-akka.actor.default-dispatcher-8] INFO  org.apache.spark.executor.Executor -  Starting executor ID <driver> on host localhost
2015-11-12 15:47:05,694 [sparkDriver-akka.actor.default-dispatcher-8] INFO  org.apache.spark.util.AkkaUtils -  Connecting to HeartbeatReceiver: akka.tcp://sparkDriver@7898949b0e5a:49993/user/HeartbeatReceiver
2015-11-12 15:47:05,967 [JobServer-akka.actor.default-dispatcher-6] INFO  org.apache.spark.network.netty.NettyBlockTransferService -  Server created on 35791
2015-11-12 15:47:05,968 [JobServer-akka.actor.default-dispatcher-6] INFO  org.apache.spark.storage.BlockManagerMaster -  Trying to register BlockManager
2015-11-12 15:47:05,970 [sparkDriver-akka.actor.default-dispatcher-8] INFO  org.apache.spark.storage.BlockManagerMasterActor -  Registering block manager localhost:35791 with 548.5 MB RAM, BlockManagerId(<driver>, localhost, 35791)
2015-11-12 15:47:05,972 [JobServer-akka.actor.default-dispatcher-6] INFO  org.apache.spark.storage.BlockManagerMaster -  Registered BlockManager
2015-11-12 15:47:06,476 [JobServer-akka.actor.default-dispatcher-9] ERROR spark.jobserver.LocalContextSupervisorActor -  Exception after sending Initialize to JobManagerActor
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://JobServer/user/context-supervisor/geoprocessing#-847005745]] after [15000 ms]
    at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:333)
    at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)
    at scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)
    at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:691)
    at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)
    at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)
    at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)
    at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)
    at java.lang.Thread.run(Thread.java:745)
2015-11-12 15:47:06,482 [JobServer-akka.actor.default-dispatcher-9] ERROR spark.jobserver.LocalContextSupervisorActor -  Unable to start context geoprocessing
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://JobServer/user/context-supervisor/geoprocessing#-847005745]] after [15000 ms]
    at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:333)
    at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)
    at scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)
    at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:691)
    at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)
    at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)
    at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)
    at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)
    at java.lang.Thread.run(Thread.java:745)
2015-11-12 15:47:06,584 [JobServer-akka.actor.default-dispatcher-9] INFO  spark.jobserver.RddManagerActor -  Starting actor spark.jobserver.RddManagerActor
2015-11-12 15:47:06,592 [JobServer-akka.actor.default-dispatcher-2] INFO  akka.actor.DeadLetterActorRef -  Message [spark.jobserver.JobManagerActor$Initialized] from Actor[akka://JobServer/user/context-supervisor/geoprocessing#-847005745] to Actor[akka://JobServer/deadLetters] was not delivered. [2] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
2015-11-12 15:47:06,614 [JobServer-akka.actor.default-dispatcher-9] WARN  spark.jobserver.RddManagerActor -  Shutting down spark.jobserver.RddManagerActor
2015-11-12 15:47:06,615 [JobServer-akka.actor.default-dispatcher-9] WARN  spark.jobserver.JobResultActor -  Shutting down spark.jobserver.JobResultActor
2015-11-12 15:47:06,615 [JobServer-akka.actor.default-dispatcher-8] WARN  spark.jobserver.JobStatusActor -  Shutting down spark.jobserver.JobStatusActor
2015-11-12 15:47:06,617 [JobServer-akka.actor.default-dispatcher-8] INFO  spark.jobserver.JobManagerActor -  Shutting down SparkContext geoprocessing
2015-11-12 15:47:06,631 [JobServer-akka.actor.default-dispatcher-8] INFO  org.spark-project.jetty.server.handler.ContextHandler -  stopped o.s.j.s.ServletContextHandler{/metrics/json,null}
2015-11-12 15:47:06,632 [JobServer-akka.actor.default-dispatcher-8] INFO  org.spark-project.jetty.server.handler.ContextHandler -  stopped o.s.j.s.ServletContextHandler{/stages/stage/kill,null}
2015-11-12 15:47:06,632 [JobServer-akka.actor.default-dispatcher-8] INFO  org.spark-project.jetty.server.handler.ContextHandler -  stopped o.s.j.s.ServletContextHandler{/,null}
2015-11-12 15:47:06,632 [JobServer-akka.actor.default-dispatcher-8] INFO  org.spark-project.jetty.server.handler.ContextHandler -  stopped o.s.j.s.ServletContextHandler{/static,null}
2015-11-12 15:47:06,633 [JobServer-akka.actor.default-dispatcher-8] INFO  org.spark-project.jetty.server.handler.ContextHandler -  stopped o.s.j.s.ServletContextHandler{/executors/threadDump/json,null}
2015-11-12 15:47:06,633 [JobServer-akka.actor.default-dispatcher-8] INFO  org.spark-project.jetty.server.handler.ContextHandler -  stopped o.s.j.s.ServletContextHandler{/executors/threadDump,null}
2015-11-12 15:47:06,634 [JobServer-akka.actor.default-dispatcher-8] INFO  org.spark-project.jetty.server.handler.ContextHandler -  stopped o.s.j.s.ServletContextHandler{/executors/json,null}
2015-11-12 15:47:06,634 [JobServer-akka.actor.default-dispatcher-8] INFO  org.spark-project.jetty.server.handler.ContextHandler -  stopped o.s.j.s.ServletContextHandler{/executors,null}
2015-11-12 15:47:06,635 [JobServer-akka.actor.default-dispatcher-8] INFO  org.spark-project.jetty.server.handler.ContextHandler -  stopped o.s.j.s.ServletContextHandler{/environment/json,null}
2015-11-12 15:47:06,635 [JobServer-akka.actor.default-dispatcher-8] INFO  org.spark-project.jetty.server.handler.ContextHandler -  stopped o.s.j.s.ServletContextHandler{/environment,null}
2015-11-12 15:47:06,635 [JobServer-akka.actor.default-dispatcher-8] INFO  org.spark-project.jetty.server.handler.ContextHandler -  stopped o.s.j.s.ServletContextHandler{/storage/rdd/json,null}
2015-11-12 15:47:06,636 [JobServer-akka.actor.default-dispatcher-8] INFO  org.spark-project.jetty.server.handler.ContextHandler -  stopped o.s.j.s.ServletContextHandler{/storage/rdd,null}
2015-11-12 15:47:06,639 [JobServer-akka.actor.default-dispatcher-8] INFO  org.spark-project.jetty.server.handler.ContextHandler -  stopped o.s.j.s.ServletContextHandler{/storage/json,null}
2015-11-12 15:47:06,643 [JobServer-akka.actor.default-dispatcher-8] INFO  org.spark-project.jetty.server.handler.ContextHandler -  stopped o.s.j.s.ServletContextHandler{/storage,null}
2015-11-12 15:47:06,643 [JobServer-akka.actor.default-dispatcher-8] INFO  org.spark-project.jetty.server.handler.ContextHandler -  stopped o.s.j.s.ServletContextHandler{/stages/pool/json,null}
2015-11-12 15:47:06,643 [JobServer-akka.actor.default-dispatcher-8] INFO  org.spark-project.jetty.server.handler.ContextHandler -  stopped o.s.j.s.ServletContextHandler{/stages/pool,null}
2015-11-12 15:47:06,644 [JobServer-akka.actor.default-dispatcher-8] INFO  org.spark-project.jetty.server.handler.ContextHandler -  stopped o.s.j.s.ServletContextHandler{/stages/stage/json,null}
2015-11-12 15:47:06,644 [JobServer-akka.actor.default-dispatcher-8] INFO  org.spark-project.jetty.server.handler.ContextHandler -  stopped o.s.j.s.ServletContextHandler{/stages/stage,null}
2015-11-12 15:47:06,644 [JobServer-akka.actor.default-dispatcher-8] INFO  org.spark-project.jetty.server.handler.ContextHandler -  stopped o.s.j.s.ServletContextHandler{/stages/json,null}
2015-11-12 15:47:06,645 [JobServer-akka.actor.default-dispatcher-8] INFO  org.spark-project.jetty.server.handler.ContextHandler -  stopped o.s.j.s.ServletContextHandler{/stages,null}
2015-11-12 15:47:06,645 [JobServer-akka.actor.default-dispatcher-8] INFO  org.spark-project.jetty.server.handler.ContextHandler -  stopped o.s.j.s.ServletContextHandler{/jobs/job/json,null}
2015-11-12 15:47:06,646 [JobServer-akka.actor.default-dispatcher-8] INFO  org.spark-project.jetty.server.handler.ContextHandler -  stopped o.s.j.s.ServletContextHandler{/jobs/job,null}
2015-11-12 15:47:06,646 [JobServer-akka.actor.default-dispatcher-8] INFO  org.spark-project.jetty.server.handler.ContextHandler -  stopped o.s.j.s.ServletContextHandler{/jobs/json,null}
2015-11-12 15:47:06,647 [JobServer-akka.actor.default-dispatcher-8] INFO  org.spark-project.jetty.server.handler.ContextHandler -  stopped o.s.j.s.ServletContextHandler{/jobs,null}
2015-11-12 15:47:06,704 [JobServer-akka.actor.default-dispatcher-8] INFO  org.apache.spark.ui.SparkUI -  Stopped Spark web UI at http://7898949b0e5a:45661
2015-11-12 15:47:06,767 [sparkDriver-akka.actor.default-dispatcher-8] INFO  org.apache.spark.MapOutputTrackerMasterActor -  MapOutputTrackerActor stopped!
2015-11-12 15:47:06,777 [JobServer-akka.actor.default-dispatcher-8] INFO  org.apache.spark.storage.MemoryStore -  MemoryStore cleared
2015-11-12 15:47:06,780 [JobServer-akka.actor.default-dispatcher-8] INFO  org.apache.spark.storage.BlockManager -  BlockManager stopped
2015-11-12 15:47:06,781 [JobServer-akka.actor.default-dispatcher-8] INFO  org.apache.spark.storage.BlockManagerMaster -  BlockManagerMaster stopped
2015-11-12 15:47:06,786 [sparkDriver-akka.actor.default-dispatcher-8] INFO  org.apache.spark.scheduler.OutputCommitCoordinator$OutputCommitCoordinatorActor -  OutputCommitCoordinator stopped!
2015-11-12 15:47:06,793 [sparkDriver-akka.actor.default-dispatcher-4] INFO  akka.remote.RemoteActorRefProvider$RemotingTerminator -  Shutting down remote daemon.
2015-11-12 15:47:06,796 [sparkDriver-akka.actor.default-dispatcher-4] INFO  akka.remote.RemoteActorRefProvider$RemotingTerminator -  Remote daemon shut down; proceeding with flushing remote transports.
2015-11-12 15:47:06,787 [JobServer-akka.actor.default-dispatcher-8] INFO  spark.jobserver.context.DefaultSparkContextFactory$$anon$1 -  Successfully stopped SparkContext
2015-11-12 15:47:06,844 [sparkDriver-akka.actor.default-dispatcher-4] INFO  akka.remote.RemoteActorRefProvider$RemotingTerminator -  Remoting shut down.
```

**Comment by ajrobbins** [comment]
No longer an issue, and Collections API work means we're doing away with SJS.
