### ISSUE TITLE
Protect against NoneType return Celery worker collection

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#1080]
If an attempt to assemble a list of active Celery workers fails, the application throws an exception. It is unclear whether the job still completes or not, but I would assume it does not:

```
Internal Server Error: /api/modeling/start/tr55/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/opt/app/apps/modeling/views.py", line 267, in start_tr55
    task_list = _initiate_tr55_job_chain(model_input, job.id)
  File "/opt/app/apps/modeling/views.py", line 278, in _initiate_tr55_job_chain
    job_chain = _construct_tr55_job_chain(model_input, job_id)
  File "/opt/app/apps/modeling/views.py", line 285, in _construct_tr55_job_chain
    routing_key = choose_worker()
  File "/opt/app/apps/modeling/views.py", line 231, in choose_worker
    celery.current_app.control.inspect().ping().keys())
AttributeError: 'NoneType' object has no attribute 'keys'
```

**Comment by kdeloach** [comment]
You can reproduce this error by:

```
./scripts/manage.sh shell
```

```
In [1]: import celery

In [2]: celery.current_app.control.inspect().ping().keys()
Out[2]: [u'Black-worker1@worker', u'Black-worker0@worker']
```

Open a new shell and run:

```
vagrant ssh worker -c 'sudo service celeryd restart'
```

While celery is restarting... re-run the above Python statement:

```
In [3]: celery.current_app.control.inspect().ping().keys()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-e0249eb9f5cb> in <module>()
----> 1 celery.current_app.control.inspect().ping().keys()

AttributeError: 'NoneType' object has no attribute 'keys'
```

**Comment by kdeloach** [comment]
I considered increasing the default timeout (1 second) but `ping` will always wait for the entire duration of the timeout to complete before returning results. Since this will needlessly slow down all celery tasks I have decided to not make this change until we have a better understanding of the consequences.
