### ISSUE TITLE
Update to latest RWD version

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1149]
New data and code are available, with a slightly different method signature.  Details to follow.

**Comment by mmcfarland** [comment]
### Instruction for running Updated Rapid Watershed Delineation(2/9/16)
#### Preprocessed data:
Updated data are available on
 http://hydrology.usu.edu/mmw2/PreProcessed_Product_RWD/   folder which contains
   Main_watershed.zip
   Subwatershed_ALL.zip
For more details, please see (https://docs.google.com/document/d/1gXhR8SZNnGs4Q7c9hj0pD8CosMeBkVbtWJCgxKnsGu4/edit#)

#### Executing Rapid Watershed Delineation:
Command line:

```python
python Rapid_Watershed_Delineation.py longitude  latitude  snapping  maximum_snap_distance Pre_process_TauDEM_dir  Ocean_stream_file  gage_watershed_file   gage_watershed_ID_file  coast_watershed_file  np  TauDEM_dir  MPI_dir   Output_dir
```

##### Command line for Delaware Specific:

```python
python Rapid_Watershed_Delineation.py -75.065647 40.512285
1 10000 /home/nazmus/DEMO_RWD “Delaware_Ocean_stream_dissolve” “delaware_gw_5000_diss” “Delaware_5000_GW_ID.txt”
“Delaware_Missing_Coast_Watershed” 8  /home/nazmus/TauDEM  /usr/local/bin      /home/nazmus/Test1
```
 ```
longitude= -75.065647 (from User)
latitude= 40.512285 (from User)
snapping= 1 (0 or 1)
maximum_snap_distance=10000 (distance to stream)
Pre_process_TauDEM_dir=/home/nazmus/DEMO_RWD (Directory, where Main_Watershed, Subwatershed_ALL directories are located)
Ocean_stream_file =  “Delaware_Ocean_stream_dissolve” ( Located in Main_Watershed )
gage_watershed_file = “delaware_gw_5000_diss” (Located in Main_Watershed)
gage_watershed_ID_file=“Delaware_5000_GW_ID.txt” ( Located in Main_Watershed )
coast_watershed_file=“Delaware_Missing_Coast_Watershed” (Located in Main_Watershed)
np=8 (number of processor)
TauDEM_dir= /home/nazmus/TauDEM (Location of TauDEM binary files)
MPI_dir=/usr/local/bin  (Location of MPI binary files)
Output_dir=/home/nazmus/Test1 (Location for new outlet point and watershed shapefile)
```

### Additional requirements for updated version:
* Make sure that ogr2ogr command line works 
* Require GDAL>=1.10 
* Need to compile GDAL with libspatialite

**Comment by kdeloach** [comment]
The volume snapshot with the latest RWD data is `snap-4a764b4a`. We'll need to update this line to use the correct snapshot ID after we have verified that the latest RWD changes work (https://github.com/WikiWatershed/model-my-watershed/blob/077df1bebf74fd0bcfb0044350caefa120cdc58d/deployment/packer/template.js#L66).

**Comment by kdeloach** [comment]
For reference, here is the actual command you would run inside the docker container to test RWD:
```
python Rapid_Watershed_Delineation.py -75.065647 40.512285 1 10000 /opt/rwd-data "Delaware_Ocean_stream_dissolve" "delaware_gw_5000_diss" "Delaware_5000_GW_ID.txt" "Delaware_Missing_Coast_Watershed" 1 /opt/taudem /usr/bin /tmp
```

**Comment by kdeloach** [comment]
I spent a few days working on this but couldn't get it to work.

First, I created a branch to merge upstream changes into our repo:
https://github.com/kdeloach/rapid-watershed-delineation/tree/merge-upstream

Then I created a branch on my docker-rwd fork to compile gdal with support for spatialite:
https://github.com/kdeloach/docker-rwd/commits/feature/rapid-rapid-watershed

I used this shell script as a reference point for updating the Dockerfile:
https://github.com/nazmussazib/RapidWatersheDelineation/commit/8c197244db271f9aad09ff501d1db0631f95d794

When I execute the RWD service `ogr2ogr` segfaults.

```
curl http://localhost:5000/rwd/39.814556386946684/-75.6863272190094
```

```
172.17.0.1 - - [04/Mar/2016 00:09:31] "GET /rwd/39.814556386946684/-75.6863272190094 HTTP/1.1" 400 -
5585
1
"/usr/local/bin/mpiexec" "--allow-run-as-root" "-np" "1" "/opt/taudem/moveoutletstostrm" "-p" "/opt/rwd-data/Subwatershed_ALL/Subwatershed5585/subwatershed_5585p.tif" "-src" "/opt/rwd-data/Subwatershed_ALL/Subwatershed5585/subwatershed_5585src1.tif" "-o" "/tmp/tmp4bEe7Z/mypoint.shp" "-om" "/tmp/tmp4bEe7Z/New_Outlet.shp" "-md" "10000.0" 
MoveOutletsToStreams version 5.3.2
Input file /opt/rwd-data/Subwatershed_ALL/Subwatershed5585/subwatershed_5585src1.tif has geographic coordinate system.
This run may take on the order of 1 minutes to complete.
This estimate is very approximate. 
Run time is highly uncertain as it depends on the complexity of the input data 
and speed and memory of the computer. This estimate is based on our testing on 
a dual quad core Dell Xeon E5405 2.0GHz PC with 16GB RAM.
Input file /opt/rwd-data/Subwatershed_ALL/Subwatershed5585/subwatershed_5585p.tif has geographic coordinate system.
New_Outlet Total time: 0.019297
Gage Watershed version 5.3.2
Input file /opt/rwd-data/Subwatershed_ALL/Subwatershed5585/subwatershed_5585p.tif has geographic coordinate system.
This run may take on the order of 1 minutes to complete.
This estimate is very approximate. 
Run time is highly uncertain as it depends on the complexity of the input data 
and speed and memory of the computer. This estimate is based on our testing on 
a dual quad core Dell Xeon E5405 2.0GHz PC with 16GB RAM.
Size: 1
Read time: 0.014760
Compute time: 0.021406
Write time: 0.013495
Total time: 0.049661
Creating output local_subwatershed.shp of format ESRI Shapefile.
0...10...20...30...40...50...60...70...80...90...100 - done.
ogr2ogr local_subwatershed_dissolve.shp local_subwatershed.shp -dialect sqlite -sql  "SELECT GRIDCODE, ST_Union(geometry) as geometry FROM   'local_subwatershed'   GROUP BY GRIDCODE"   -nln results -overwrite
Segmentation fault (core dumped)
Error running Point_Watershed_Function
Traceback (most recent call last):
  File "main.py", line 66, in run_rwd
    output_path,
  File "/opt/rwd/rwd/Rapid_Watershed_Delineation.py", line 159, in Point_Watershed_Function
    New_Gage_watershed_Dissolve,up_ID,Pre_process_TauDEM_dir,dir_name,ID,Output_dir)
  File "/opt/rwd/rwd/RWSDelin_Utilities.py", line 248, in Reach_Upstream_Edge
    layer12 = file11.GetLayerByName(New_Gage_watershed_Dissolve)
AttributeError: 'NoneType' object has no attribute 'GetLayerByName'
```

Running `ogr2ogr` in isolation:

```bash
root@b47a81b2b696:/opt/rwd/src/api# cd /tmp/tmp4bEe7Z/
root@b47a81b2b696:/tmp/tmp4bEe7Z# ogr2ogr local_subwatershed_dissolve.shp local_subwatershed.shp -dialect sqlite -sql  "SELECT GRIDCODE, ST_Union(geometry) as geometry FROM   'local_subwatershed'   GROUP BY GRIDCODE"   -nln results -overwrite
Segmentation fault (core dumped)
root@b47a81b2b696:/tmp/tmp4bEe7Z# dmesg | tail
[118116.914301] docker0: port 2(veth95cb066) entered forwarding state
[118116.914308] docker0: port 2(veth95cb066) entered forwarding state
[118116.916055] docker0: port 2(veth95cb066) entered disabled state
[118117.097306] IPv6: ADDRCONF(NETDEV_CHANGE): veth95cb066: link becomes ready
[118117.097360] docker0: port 2(veth95cb066) entered forwarding state
[118117.097377] docker0: port 2(veth95cb066) entered forwarding state
[118130.692724] ogr2ogr[22373]: segfault at 600 ip 00007fe2b1989ef1 sp 00007ffce3800868 error 4 in libgdal.so.1.17.0[7fe2b1214000+a10000]
[118132.131652] docker0: port 2(veth95cb066) entered forwarding state
[118147.977694] ogr2ogr[22840]: segfault at 600 ip 00007f7da9ef2ef1 sp 00007ffd7154b558 error 4 in libgdal.so.1.17.0[7f7da977d000+a10000]
[118671.896371] ogr2ogr[1012]: segfault at 600 ip 00007f5811463ef1 sp 00007ffdedd2c568 error 4 in libgdal.so.1.17.0[7f5810cee000+a10000]
```

Note that `spatialite` seems to be installed correctly. I'm able to load a shape file and perform spatial queries against it.

```bash
root@b47a81b2b696:/tmp/tmp4bEe7Z# spatialite --version
SpatiaLite version ..: 4.1.1	Supported Extensions:
	- 'VirtualShape'	[direct Shapefile access]
	- 'VirtualDbf'		[direct DBF access]
	- 'VirtualXL'		[direct XLS access]
	- 'VirtualText'		[direct CSV/TXT access]
	- 'VirtualNetwork'	[Dijkstra shortest path]
	- 'RTree'		[Spatial Index - R*Tree]
	- 'MbrCache'		[Spatial Index - MBR cache]
	- 'VirtualSpatialIndex'	[R*Tree metahandler]
	- 'VirtualXPath'	[XML Path Language - XPath]
	- 'VirtualFDO'		[FDO-OGR interoperability]
	- 'SpatiaLite'		[Spatial SQL - OGC]
PROJ.4 version ......: Rel. 4.8.0, 6 March 2012
GEOS version ........: 3.4.2-CAPI-1.8.2 r3921
3.8.7.1 2014-10-29 13:59:56 3b7b72c4685aa5cf5e675c2c47ebec10d9704221
```

I have a suspicion that gdal is not correctly compiling with spatialite support. "Spatialite" is missing from the list of supported `ogr` formats:

```bash
root@b47a81b2b696:/tmp/tmp4bEe7Z# ogrinfo --formats | grep -i lite
  -> "SQLite" (read/write)
```

I tried compiling and installing gdal in various ways but was not successful in resolving this issue.

**Comment by kdeloach** [comment]
I tried running the shell provisioning script (https://raw.githubusercontent.com/nazmussazib/RapidWatersheDelineation/8c197244db271f9aad09ff501d1db0631f95d794/RWD_pre_requisite_Updated.sh) inside a Vagrant VM (precise64 base box) but ran into a few issues.

```
vagrant@precise64:~$ sudo pip install pandas
Downloading/unpacking pandas
  Downloading pandas-0.17.1.tar.gz (6.7Mb): 6.7Mb downloaded
  Running setup.py egg_info for package pandas
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/vagrant/build/pandas/setup.py", line 589, in <module>
        **setuptools_kwargs)
      File "/usr/lib/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 221, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 245, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 588, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (numpy 1.6.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('numpy>=1.7.0'))
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/vagrant/build/pandas/setup.py", line 589, in <module>

    **setuptools_kwargs)

  File "/usr/lib/python2.7/distutils/core.py", line 112, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 221, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 245, in fetch_build_eggs

    parse_requirements(requires), installer=self.fetch_build_egg

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 588, in resolve

    raise VersionConflict(dist,req) # XXX put more info here

pkg_resources.VersionConflict: (numpy 1.6.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('numpy>=1.7.0'))

----------------------------------------
Command python setup.py egg_info failed with error code 1
```

I was able to fix this by running `pip install numpy --upgrade`.

Then I get this error when trying to install `shapely`:

```
vagrant@precise64:~$ sudo pip install shapely
Downloading/unpacking shapely
  Downloading Shapely-1.5.13.tar.gz (176Kb): 176Kb downloaded
  Running setup.py egg_info for package shapely
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/vagrant/build/shapely/setup.py", line 38, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "shapely/_buildcfg.py", line 88, in <module>
        clibs = get_geos_config('--clibs')
      File "shapely/_buildcfg.py", line 77, in get_geos_config
        raise ValueError(stderr.strip())
    ValueError: Usage: geos-config [OPTIONS]
    Options:
         [--prefix]
         [--version]
         [--libs]
         [--cflags]
         [--ldflags]
         [--includes]
         [--jtsport]
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/vagrant/build/shapely/setup.py", line 38, in <module>

    from shapely._buildcfg import geos_version_string, geos_version, \

  File "shapely/_buildcfg.py", line 88, in <module>

    clibs = get_geos_config('--clibs')

  File "shapely/_buildcfg.py", line 77, in get_geos_config

    raise ValueError(stderr.strip())

ValueError: Usage: geos-config [OPTIONS]

Options:

     [--prefix]

     [--version]

     [--libs]

     [--cflags]

     [--ldflags]

     [--includes]

     [--jtsport]

----------------------------------------
Command python setup.py egg_info failed with error code 1
```

We will need to figure out the exact version numbers for each dependency to resolve this issue.
