### ISSUE TITLE
Exception: Job failed, deleted.

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#1159]
View details in Rollbar: [https://rollbar.com/Azavea/MMW/items/34/](https://rollbar.com/Azavea/MMW/items/34/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "apps/modeling/tasks.py", line 90, in get_histogram_job_results
    histogram = histogram_finish(incoming['sjs_job_id'], self.retry)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 26, in wrapper
    return f(*args, **kw)
  File "apps/modeling/geoprocessing.py", line 131, in histogram_finish
    raise Exception('Job failed, deleted.')
Exception: Job failed, deleted.
```

**Comment by hectcastro** [comment]
More context from around that time:

```
java.util.concurrent.ExecutionException: Boxed Error
        at scala.concurrent.impl.Promise$.resolver(Promise.scala:55)
        at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:47)
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244)
        at scala.concurrent.Promise$class.complete(Promise.scala:55)
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError: assertion failed: Polygon Empty: POLYGON EMPTY
```

**Comment by hectcastro** [comment]
More context:

```
	java.lang.UnsupportedOperationException: empty collection
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1$$anonfun$apply$36.apply(RDD.scala:1009)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1$$anonfun$apply$36.apply(RDD.scala:1009)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1009)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:310)
	at org.apache.spark.rdd.RDD.reduce(RDD.scala:989)
	at org.wikiwatershed.mmw.geoprocessing.SummaryJob$.histograms(SummaryJob.scala:158)
	at org.wikiwatershed.mmw.geoprocessing.SummaryJob$.runJob(SummaryJob.scala:34)
	at org.wikiwatershed.mmw.geoprocessing.SummaryJob$.runJob(SummaryJob.scala:18)
	at spark.jobserver.JobManagerActor$$anonfun$spark$jobserver$JobManagerActor$$getJobFuture$4.apply(JobManagerActor.scala:254)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mmcfarland** [comment]
This error is tightly coupled to the SJS implementation, which we have removed.  If the underlying cause of the failure persists, it will express itself as a new exception type and we'll track it there.
