### ISSUE TITLE
Error when choosing Worker for RWD job (AttributeError: <type 'exceptions.AttributeError'>)

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1169]
View details in Rollbar: [https://rollbar.com/Azavea/MMW/items/42/](https://rollbar.com/Azavea/MMW/items/42/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/opt/app/apps/modeling/views.py", line 175, in start_rwd
    task_list = _initiate_rwd_job_chain(location, snapping, job.id)
  File "/opt/app/apps/modeling/views.py", line 258, in _initiate_rwd_job_chain
    routing_key = choose_worker()
  File "/opt/app/apps/modeling/views.py", line 239, in choose_worker
    celery.current_app.control.inspect().ping().keys())
AttributeError: <type 'exceptions.AttributeError'>
```

**Comment by mmcfarland** [comment]
This is no longer happening after a recent staging deploy.  Not sure of the cause, but let's keep an eye out for its return.

**Comment by mmcfarland** [comment]
Attempted resolution in https://github.com/WikiWatershed/model-my-watershed/pull/1186
