### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'int' and 'list'

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#1225]
View details in Rollbar: [https://rollbar.com/Azavea/MMW/items/50/](https://rollbar.com/Azavea/MMW/items/50/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "apps/modeling/tasks.py", line 61, in start_histogram_job
    'pixel_width': aoi_resolution(polygon),
  File "apps/modeling/tasks.py", line 127, in aoi_resolution
    average_lat = reduce(lambda total, p: total+p[1], pairs, 0) / len(pairs)
  File "apps/modeling/tasks.py", line 127, in <lambda>
    average_lat = reduce(lambda total, p: total+p[1], pairs, 0) / len(pairs)
TypeError: unsupported operand type(s) for +: 'int' and 'list'
```

**Comment by caseypt** [comment]
I got this error shortly after 1.12.0 dark stack came up by using the RWD feature. A watershed was returned by the analyze task failed almost immediately.

**Comment by kellyi** [comment]
Some notes:

At https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/modeling/tasks.py#L151 I dropped this print statement to check the value of `pairs`:

```
print('aoi_resolution/pairs => {}'.format(pairs))
```

The output from `debugcelery` for this AOI:

![screen shot 2016-09-15 at 4 28 14 pm](https://cloud.githubusercontent.com/assets/4165523/18566321/6bb11f54-7b61-11e6-9177-9d1dedc36a7e.png)

...was

```
[[-75.19698361798585, 39.986452096497686], [-75.18524904802976, 39.986452096497686], [-75.18524904802976, 39.99544249027034], [-75.19698361798585, 39.99544249027034], [-75.19698361798585, 39.986452096497686]]
```

I thought it might be related to the list being wrapped in an additional array in some instances, so I tried this out in the REPL, and...

```
Python 2.7.10 (default, Oct 23 2015, 18:05:06) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> pairs = [[-75.19698361798585, 39.986452096497686], [-75.18524904802976, 39.986452096497686], [-75.18524904802976, 39.99544249027034], [-75.19698361798585, 39.99544249027034], [-75.19698361798585, 39.986452096497686]]
>>> print reduce(lambda total, p: total+p[1], pairs, 0) / len(pairs)
39.990048254
>>> nested_pairs = [pairs]
>>> print reduce(lambda total, p: total+p[1], nested_pairs, 0) / len(nested_pairs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <lambda>
TypeError: unsupported operand type(s) for +: 'int' and 'list'
>>> 
```

**Comment by kellyi** [comment]
The app currently creates the pairs by doing `area_of_interest['coordinates'][0][0]`, on shapes nested in a 4d array but the error seems like it may happen on shapes which include a 5d array. This is from the most recent Rollbar error:

```
...\"coordinates\":[[[[[-75.25722222219511,39.9766666666191,[-75.25712962960245,39.9766666666191...
```
