### ISSUE TITLE
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#1226]
View details in Rollbar: [https://rollbar.com/Azavea/MMW/items/49/](https://rollbar.com/Azavea/MMW/items/49/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "apps/modeling/tasks.py", line 41, in start_rwd_job
    response_json = requests.get(rwd_url).json()
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by hectcastro** [comment]
This may because the RWD jobs are taking longer than the Gunicorn workers are allowing. Their default timeouts for a given request may need to increase so account for the upper bound of RWD job duration.

```
Apr  7 15:59:12 ip-10-0-1-206 docker/a5a4a8dff24a[927]: [2016-04-07 15:59:12 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:13)
```

**Comment by mmcfarland** [comment]
I just tried out of a few of the failing submission URLs captured by RollBar and they all seem to complete successfully in under 10 seconds.

```
curl 'https://staging.app.wikiwatershed.org/api/modeling/start/rwd/' --data 'location=[39.798381437470134,-75.65760612487793]&snappingOn=true' --compressed
```
followed by a GET on the resulting GUID:
```
curl 'https://staging.app.wikiwatershed.org/api/modeling/jobs/6f275abc-fe49-4184-8e15-0c3f3dc6ade8/'
```

I think we've suspected that this is a timeout related to times when the data is not copied to the worker in time to respond to the request, and these results reinforce those suspicions.  Depending on how https://github.com/WikiWatershed/rapid-watershed-delineation/issues/31 resolves, this problem may be eliminated or need to be addressed in a different way.
