### ISSUE TITLE
Miami Watersheds Fail

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#1383]
On choosing any of a number of watersheds in Miami, such as this one:

![image](https://cloud.githubusercontent.com/assets/1430060/16428775/6ed47de2-3d41-11e6-8794-02b56e1e14d1.png)

We get the following message in Celery:

```
[2016-06-28 14:34:03,426: ERROR/Worker-1] Task bd69816d-34a7-42f4-850d-79a5af7c1ad9 run from job 3765 raised exception: 'DataModel' object has no attribute 'AdjUrbanQTotal'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app/apps/modeling/tasks.py", line 351, in run_gwlfe
    result = gwlfe.run(z)
  File "/usr/local/lib/python2.7/dist-packages/gwlfe/gwlfe.py", line 126, in run
    CalcCnErosRunoffSed.CalcCN(z, i, Y, j)
  File "/usr/local/lib/python2.7/dist-packages/gwlfe/CalcCnErosRunoffSed.py", line 102, in CalcCN
    BasinWater(z, i, Y, j)
  File "/usr/local/lib/python2.7/dist-packages/gwlfe/CalcCnErosRunoffSed.py", line 257, in BasinWater
    if z.AdjUrbanQTotal > 0.001:
AttributeError: 'DataModel' object has no attribute 'AdjUrbanQTotal'
```

This is the exported GMS: [RoyalGladesCanal.gms.txt](https://github.com/WikiWatershed/model-my-watershed/files/337845/RoyalGladesCanal.gms.txt)

Find out what is unique about watersheds in this area, and provide appropriate defaults to ensure this doesn't happen.

**Comment by kellyi** [comment]
Note: Since I've got Congressional Districts installed and not HUC-12s, FL-24 roughly maps on to the Watershed drawn above -- and also fails in MapShed.

**Comment by kellyi** [comment]
`z.AdjUrbanQTotal` doesn't seem to be assigned in GWLF-E because it happens in an if statement for `z.BasinArea > 0` that's not getting called for this GMS file.

**Comment by kellyi** [comment]
Looks like z.AdjUrbanQTotal's not getting assigned because the assignment happens in an if statement that's not triggered for this gms file.
