### ISSUE TITLE
Update DRB stream data

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1410]
@dtarb will provide an updated set of vector stream data as a shapfile which fixes some current issues with DRB streams.

**Comment by dtarb** [comment]
It is actually a completely new dataset.  Base data products are in:
http://hydrology.usu.edu/mmw2/Geographic/

Preprocessed data for rapid delineation are in 
http://hydrology.usu.edu/mmw2/PreProcessed_Product_RWD/

The files and formats should be exactly the same as before.

**Comment by mmcfarland** [comment]
This is the shapefile that we use for DRB Streams: http://hydrology.usu.edu/mmw2/Geographic/DelDEMGeo4net50.zip

**Comment by dtarb** [comment]
Yes.  This should be an update of the shapefile you currently have (that may have the same name).

**Comment by mmcfarland** [comment]
The data has been updated and put in s3, to test:

- Run `./setupdb.sh -d`
- Verify `drb_streams_50` has 595300 rows
- Verify the tiler display of the streams works

**Comment by lewfish** [comment]
Works for me.

**Comment by lewfish** [comment]
I spoke too soon. I'm getting the following error on the backend when running Mapshed on a 1km AOI in Philly.

```
Internal Server Error: /api/modeling/start/mapshed/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/opt/app/apps/modeling/views.py", line 243, in start_mapshed
    task_list = _initiate_mapshed_job_chain(mapshed_input, job.id)
  File "/opt/app/apps/modeling/views.py", line 268, in _initiate_mapshed_job_chain
    routing_key=choose_worker()) |
  File "/opt/app/apps/modeling/mapshed/tasks.py", line 475, in geop_tasks
    'vector': streams(geom, drb=True)},
  File "/opt/app/apps/modeling/mapshed/calcs.py", line 302, in streams
    cursor.execute(sql, [geom.wkt, geom.wkt])
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
InternalError: Operation on mixed SRID geometries
```

**Comment by lewfish** [comment]
This line seems relevant:
``` 
File "/opt/app/apps/modeling/mapshed/tasks.py", line 475, in geop_tasks
    'vector': streams(geom, drb=True)},
```

**Comment by mmcfarland** [comment]
Good catch, I forgot to reproject the data. Will update it now.

**Comment by mmcfarland** [comment]
Data updated and reloaded.  Try again with a `-d` to load and test the tiler + mapshed.

**Comment by dtarb** [comment]
@mmcfarland you may know this already, but you will also need to add to the system the updated data in the http://hydrology.usu.edu/mmw2/PreProcessed_Product_RWD/ folder.  Without this the RWD watersheds will not align with the streams in the shapefile you are loading.

**Comment by lewfish** [comment]
Running `setupdb.sh -s` worked except at the end it complained that `aws` is not installed.

**Comment by mmcfarland** [comment]
The aws error is expected if you ran it from your app vm - its job is to clear out the tile cache for that layer when run on staging or prod environments, which we don't want from dev.

**Comment by lewfish** [comment]
+1, tested
