### ISSUE TITLE
Exception: Job xxx was ERROR (java.lang.Throwable: empty collection), deleted

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1470]
View details in Rollbar: [https://rollbar.com/Azavea/MMW/items/96/](https://rollbar.com/Azavea/MMW/items/96/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "apps/modeling/tasks.py", line 96, in get_histogram_job_results
    histogram = histogram_finish(incoming['sjs_job_id'], self.retry)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 26, in wrapper
    return f(*args, **kw)
  File "apps/modeling/geoprocessing.py", line 164, in histogram_finish
    data = sjs_retrieve(host, port, job_id, retry)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 26, in wrapper
    return f(*args, **kw)
  File "apps/modeling/geoprocessing.py", line 124, in sjs_retrieve
    raise Exception('Job {} was {}, deleted'.format(job_id, status))
Exception: Job faf47062-6253-4ccb-a30e-e70548cbbbfe was ERROR (java.lang.Throwable: empty collection), deleted
```

**Comment by jtarricone** [comment]
I think this might be due to spark quietly running into resource constraints. I started testing different changes to the configuration that would increase the number of partitions per CPU, the amount of memory available to the spark driver, etc. but actually getting the new configuration reflected in the environment was tedious so I didn't get to actually test whether performance was affected.

**Comment by kellyi** [comment]
Some additional notes:

First occurrence was on July 4, 2016: https://rollbar.com/Azavea/MMW/items/96/occurrences/14353190288/

Looks like we released MapShed on June 29: https://github.com/WikiWatershed/model-my-watershed/releases/tag/1.13.0

**Comment by kellyi** [comment]
I am able to recreate this error -- https://rollbar.com/Azavea/MMW/items/96/ -- on production by drawing a shape like this:

<img width="1269" alt="screen shot 2016-09-21 at 2 56 56 pm" src="https://cloud.githubusercontent.com/assets/4165523/18724796/b2bf08ee-800b-11e6-868a-4460560f8c0d.png">

The more detailed error message for recent occurrences of this exception on production is:

```
Exception: Job 91b9838b-b3e2-4337-837d-8dc5cbc5f322 was ERROR (java.lang.Throwable: Job aborted due to stage failure: Task 1 in stage 9369.0 failed 1 times, most recent failure: Lost task 1.0 in stage 9369.0 (TID 18657, localhost): UnknownReason
Driver stacktrace:), deleted
```

**Comment by kellyi** [comment]
Drawing a similar shape on staging --

<img width="1244" alt="screen shot 2016-09-21 at 3 00 38 pm" src="https://cloud.githubusercontent.com/assets/4165523/18724922/345e5ad0-800c-11e6-92a8-9cc8eee7146a.png">

-- leads to a pair of errors:

First, this one -- https://rollbar.com/Azavea/MMW/items/119/ -- which is 

```
InternalError: Error performing intersection: TopologyException: Input geom 1 is invalid: Self-intersection at or near point -75.067873012115129 40.024242496117367 at -75.067873012115129 40.024242496117367
```

Second, this one -- https://rollbar.com/Azavea/MMW/items/68/ -- which is

```
Exception: Job 048296bb-ee16-400b-b98e-ecb5f8b87440 was ERROR (java.lang.Throwable: Job aborted due to stage failure: Task 0 in stage 22.0 failed 1 times, most recent failure: Lost task 0.0 in stage 22.0 (TID 22, localhost): UnknownReason
Driver stacktrace:), deleted
```

**Comment by kellyi** [comment]
Trying to run MapShed on the production aoi above leads to this error message:

```
Exception: Job faf47062-6253-4ccb-a30e-e70548cbbbfe was ERROR (java.lang.Throwable: empty collection), deleted
```

and trying to model the staging aoi above leads to this one again:

```
Exception: Job 048296bb-ee16-400b-b98e-ecb5f8b87440 was ERROR (java.lang.Throwable: Job aborted due to stage failure: Task 0 in stage 22.0 failed 1 times, most recent failure: Lost task 0.0 in stage 22.0 (TID 22, localhost): UnknownReason
Driver stacktrace:), deleted
```

**Comment by kellyi** [comment]
Drawing this AOI on the `develop` branch on my local --

![screen shot 2016-09-21 at 3 08 00 pm](https://cloud.githubusercontent.com/assets/4165523/18725181/3697577e-800d-11e6-9bfa-4a4eb338fc0f.png)

-- leads to these error messages in `debugcelery.sh`:

```bash
[2016-09-21 15:07:56,040: ERROR/MainProcess] Task apps.modeling.tasks.analyze_animals[0c4f6896-f632-4b0e-80c1-d63bc2b94945] raised unexpected: InternalError('Error performing intersection: TopologyException: Input geom 1 is invalid: Self-intersection at or near point -75.199210580858889 40.00435378095213 at -75.199210580858889 40.00435378095213\n',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app/apps/modeling/tasks.py", line 141, in analyze_animals
    return [animal_population(area_of_interest)]
  File "/opt/app/apps/modeling/calcs.py", line 28, in animal_population
    aeu_for_geom = animal_energy_units(geom)[2]
  File "/opt/app/apps/modeling/mapshed/calcs.py", line 181, in animal_energy_units
    cursor.execute(sql, [geom.wkt, geom.wkt])
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
InternalError: Error performing intersection: TopologyException: Input geom 1 is invalid: Self-intersection at or near point -75.199210580858889 40.00435378095213 at -75.199210580858889 40.00435378095213

[2016-09-21 15:07:56,052: ERROR/Worker-1] Task 0c4f6896-f632-4b0e-80c1-d63bc2b94945 run from job 1203 raised exception: Error performing intersection: TopologyException: Input geom 1 is invalid: Self-intersection at or near point -75.199210580858889 40.00435378095213 at -75.199210580858889 40.00435378095213

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app/apps/modeling/tasks.py", line 141, in analyze_animals
    return [animal_population(area_of_interest)]
  File "/opt/app/apps/modeling/calcs.py", line 28, in animal_population
    aeu_for_geom = animal_energy_units(geom)[2]
  File "/opt/app/apps/modeling/mapshed/calcs.py", line 181, in animal_energy_units
    cursor.execute(sql, [geom.wkt, geom.wkt])
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
InternalError: Error performing intersection: TopologyException: Input geom 1 is invalid: Self-intersection at or near point -75.199210580858889 40.00435378095213 at -75.199210580858889 40.00435378095213


[2016-09-21 15:07:56,056: DEBUG/MainProcess] Task accepted: apps.core.tasks.save_job_error[3120997e-3110-43e1-b168-50ff64f89fd5] pid:6401
[2016-09-21 15:07:56,095: INFO/MainProcess] Task apps.core.tasks.save_job_error[3120997e-3110-43e1-b168-50ff64f89fd5] succeeded in 0.0447876819999s: None
[2016-09-21 15:07:56,396: DEBUG/MainProcess] Task accepted: apps.modeling.tasks.get_histogram_job_results[f46855f5-599c-47e9-9e55-441bbcee89d4] pid:6401
[2016-09-21 15:07:56,447: INFO/MainProcess] Received task: apps.core.tasks.save_job_error[7f845566-3dfd-4ee9-8f60-9757da626e80]
[2016-09-21 15:07:56,450: ERROR/MainProcess] Task apps.modeling.tasks.get_histogram_job_results[f46855f5-599c-47e9-9e55-441bbcee89d4] raised unexpected: Exception(u'Job 987cae89-852c-408a-b8d5-a002fd90bef9 was ERROR (java.lang.Throwable: Job aborted due to stage failure: Task 0 in stage 48.0 failed 1 times, most recent failure: Lost task 0.0 in stage 48.0 (TID 34, localhost): UnknownReason\nDriver stacktrace:), deleted',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app/apps/modeling/tasks.py", line 102, in get_histogram_job_results
    histogram = histogram_finish(incoming['sjs_job_id'], self.retry)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 26, in wrapper
    return f(*args, **kw)
  File "/opt/app/apps/modeling/geoprocessing.py", line 164, in histogram_finish
    data = sjs_retrieve(host, port, job_id, retry)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 26, in wrapper
    return f(*args, **kw)
  File "/opt/app/apps/modeling/geoprocessing.py", line 124, in sjs_retrieve
    raise Exception('Job {} was {}, deleted'.format(job_id, status))
Exception: Job 987cae89-852c-408a-b8d5-a002fd90bef9 was ERROR (java.lang.Throwable: Job aborted due to stage failure: Task 0 in stage 48.0 failed 1 times, most recent failure: Lost task 0.0 in stage 48.0 (TID 34, localhost): UnknownReason
Driver stacktrace:), deleted
[2016-09-21 15:07:56,463: DEBUG/MainProcess] Task accepted: apps.core.tasks.save_job_error[7f845566-3dfd-4ee9-8f60-9757da626e80] pid:6401
[2016-09-21 15:07:56,465: ERROR/Worker-1] Task f46855f5-599c-47e9-9e55-441bbcee89d4 run from job 1202 raised exception: Job 987cae89-852c-408a-b8d5-a002fd90bef9 was ERROR (java.lang.Throwable: Job aborted due to stage failure: Task 0 in stage 48.0 failed 1 times, most recent failure: Lost task 0.0 in stage 48.0 (TID 34, localhost): UnknownReason
Driver stacktrace:), deleted
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app/apps/modeling/tasks.py", line 102, in get_histogram_job_results
    histogram = histogram_finish(incoming['sjs_job_id'], self.retry)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 26, in wrapper
    return f(*args, **kw)
  File "/opt/app/apps/modeling/geoprocessing.py", line 164, in histogram_finish
    data = sjs_retrieve(host, port, job_id, retry)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 26, in wrapper
    return f(*args, **kw)
  File "/opt/app/apps/modeling/geoprocessing.py", line 124, in sjs_retrieve
    raise Exception('Job {} was {}, deleted'.format(job_id, status))
Exception: Job 987cae89-852c-408a-b8d5-a002fd90bef9 was ERROR (java.lang.Throwable: Job aborted due to stage failure: Task 0 in stage 48.0 failed 1 times, most recent failure: Lost task 0.0 in stage 48.0 (TID 34, localhost): UnknownReason
Driver stacktrace:), deleted
```

**Comment by kellyi** [comment]
Running MapShed on the above local/develop AOI leads to this error output:

```sh
[2016-09-21 15:10:11,437: ERROR/MainProcess] Task apps.modeling.tasks.analyze_animals[3505cee0-3bb1-4a61-928a-34321d374546] raised unexpected: InternalError('Error performing intersection: TopologyException: Input geom 1 is invalid: Self-intersection at or near point -75.199210580858889 40.00435378095213 at -75.199210580858889 40.00435378095213\n',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app/apps/modeling/tasks.py", line 141, in analyze_animals
    return [animal_population(area_of_interest)]
  File "/opt/app/apps/modeling/calcs.py", line 28, in animal_population
    aeu_for_geom = animal_energy_units(geom)[2]
  File "/opt/app/apps/modeling/mapshed/calcs.py", line 181, in animal_energy_units
    cursor.execute(sql, [geom.wkt, geom.wkt])
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
InternalError: Error performing intersection: TopologyException: Input geom 1 is invalid: Self-intersection at or near point -75.199210580858889 40.00435378095213 at -75.199210580858889 40.00435378095213

[2016-09-21 15:10:11,450: ERROR/Worker-1] Task 3505cee0-3bb1-4a61-928a-34321d374546 run from job 1207 raised exception: Error performing intersection: TopologyException: Input geom 1 is invalid: Self-intersection at or near point -75.199210580858889 40.00435378095213 at -75.199210580858889 40.00435378095213

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app/apps/modeling/tasks.py", line 141, in analyze_animals
    return [animal_population(area_of_interest)]
  File "/opt/app/apps/modeling/calcs.py", line 28, in animal_population
    aeu_for_geom = animal_energy_units(geom)[2]
  File "/opt/app/apps/modeling/mapshed/calcs.py", line 181, in animal_energy_units
    cursor.execute(sql, [geom.wkt, geom.wkt])
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
InternalError: Error performing intersection: TopologyException: Input geom 1 is invalid: Self-intersection at or near point -75.199210580858889 40.00435378095213 at -75.199210580858889 40.00435378095213


[2016-09-21 15:10:11,452: DEBUG/MainProcess] Task accepted: apps.core.tasks.save_job_error[bece7f28-e441-4e25-a85f-93a7817c6165] pid:6401
[2016-09-21 15:10:11,480: INFO/MainProcess] Task apps.core.tasks.save_job_error[bece7f28-e441-4e25-a85f-93a7817c6165] succeeded in 0.0323967980003s: None
[2016-09-21 15:10:12,582: DEBUG/MainProcess] Task accepted: apps.modeling.tasks.get_histogram_job_results[2c56390c-f286-4b8e-8705-e90f7b51d4fd] pid:6401
[2016-09-21 15:10:12,615: INFO/MainProcess] Received task: apps.core.tasks.save_job_error[e72650bf-0e47-4642-9521-493915e8fc83]
[2016-09-21 15:10:12,618: ERROR/MainProcess] Task apps.modeling.tasks.get_histogram_job_results[2c56390c-f286-4b8e-8705-e90f7b51d4fd] raised unexpected: Exception(u'Job c008a5f6-c10d-41e9-864e-d6b02cda9aa7 was ERROR (java.lang.Throwable: Job aborted due to stage failure: Task 0 in stage 51.0 failed 1 times, most recent failure: Lost task 0.0 in stage 51.0 (TID 37, localhost): UnknownReason\nDriver stacktrace:), deleted',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app/apps/modeling/tasks.py", line 102, in get_histogram_job_results
    histogram = histogram_finish(incoming['sjs_job_id'], self.retry)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 26, in wrapper
    return f(*args, **kw)
  File "/opt/app/apps/modeling/geoprocessing.py", line 164, in histogram_finish
    data = sjs_retrieve(host, port, job_id, retry)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 26, in wrapper
    return f(*args, **kw)
  File "/opt/app/apps/modeling/geoprocessing.py", line 124, in sjs_retrieve
    raise Exception('Job {} was {}, deleted'.format(job_id, status))
Exception: Job c008a5f6-c10d-41e9-864e-d6b02cda9aa7 was ERROR (java.lang.Throwable: Job aborted due to stage failure: Task 0 in stage 51.0 failed 1 times, most recent failure: Lost task 0.0 in stage 51.0 (TID 37, localhost): UnknownReason
Driver stacktrace:), deleted
[2016-09-21 15:10:12,635: ERROR/Worker-1] Task 2c56390c-f286-4b8e-8705-e90f7b51d4fd run from job 1206 raised exception: Job c008a5f6-c10d-41e9-864e-d6b02cda9aa7 was ERROR (java.lang.Throwable: Job aborted due to stage failure: Task 0 in stage 51.0 failed 1 times, most recent failure: Lost task 0.0 in stage 51.0 (TID 37, localhost): UnknownReason
Driver stacktrace:), deleted
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app/apps/modeling/tasks.py", line 102, in get_histogram_job_results
    histogram = histogram_finish(incoming['sjs_job_id'], self.retry)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 26, in wrapper
    return f(*args, **kw)
  File "/opt/app/apps/modeling/geoprocessing.py", line 164, in histogram_finish
    data = sjs_retrieve(host, port, job_id, retry)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 26, in wrapper
    return f(*args, **kw)
  File "/opt/app/apps/modeling/geoprocessing.py", line 124, in sjs_retrieve
    raise Exception('Job {} was {}, deleted'.format(job_id, status))
Exception: Job c008a5f6-c10d-41e9-864e-d6b02cda9aa7 was ERROR (java.lang.Throwable: Job aborted due to stage failure: Task 0 in stage 51.0 failed 1 times, most recent failure: Lost task 0.0 in stage 51.0 (TID 37, localhost): UnknownReason
Driver stacktrace:), deleted
```
