### ISSUE TITLE
Exception: Unable to submit job to Spark JobServer.
Details = {
  "status": "ERROR",
  "result": "context geoprocessing not found"
}

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1476]
View details in Rollbar: [https://rollbar.com/Azavea/MMW/items/118/](https://rollbar.com/Azavea/MMW/items/118/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "apps/modeling/tasks.py", line 73, in start_histogram_job
    'sjs_job_id': histogram_start([json.dumps(polygon)], self.retry)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 26, in wrapper
    return f(*args, **kw)
  File "apps/modeling/geoprocessing.py", line 146, in histogram_start
    return sjs_submit(host, port, args, data, retry)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 26, in wrapper
    return f(*args, **kw)
  File "apps/modeling/geoprocessing.py", line 76, in sjs_submit
    'Details = {}'.format(response.text))
Exception: Unable to submit job to Spark JobServer.
Details = {
  "status": "ERROR",
  "result": "context geoprocessing not found"
}
```

**Comment by ajrobbins** [comment]
This seems to be happening the first time something is requested after a new deployment.

**Comment by hectcastro** [comment]
Attempts at mitigating this could consist of:

- Checking to see if the geoprocessing context exists before submitting a task
- Enhancing the health check used for the workers

**Comment by kellyi** [comment]
I was able to reproduce this error on my local by deleting the `geoprocessing` context with `httpie`:

```sh
http DELETE :8090/contexts/geoprocessing
```

Visiting http://localhost:8090/contexts/ to see the list of available contexts then just showed an empty array, and when I tried to analyze an AOI I got this error message in `debugcelery.sh`:

```sh
[2016-09-28 10:47:08,221: ERROR/MainProcess] Task apps.modeling.tasks.start_histogram_job[6da1f81f-2acc-4ca2-a022-c7a9de62a02d] raised unexpected: Exception(u'Unable to submit job to Spark JobServer.\nDetails = {\n  "status": "ERROR",\n  "result": "context geoprocessing not found"\n}',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app/apps/modeling/tasks.py", line 73, in start_histogram_job
    'sjs_job_id': histogram_start([json.dumps(polygon)], self.retry)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 26, in wrapper
    return f(*args, **kw)
  File "/opt/app/apps/modeling/geoprocessing.py", line 146, in histogram_start
    
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 26, in wrapper
    return f(*args, **kw)
  File "/opt/app/apps/modeling/geoprocessing.py", line 76, in sjs_submit
    context_response = requests.post(geop_context_url, data='')
Exception: Unable to submit job to Spark JobServer.
Details = {
  "status": "ERROR",
  "result": "context geoprocessing not found"
}
[2016-09-28 10:47:08,229: ERROR/Worker-1] Task 6da1f81f-2acc-4ca2-a022-c7a9de62a02d run from job 1649 raised exception: Unable to submit job to Spark JobServer.
Details = {
  "status": "ERROR",
  "result": "context geoprocessing not found"
}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app/apps/modeling/tasks.py", line 73, in start_histogram_job
    'sjs_job_id': histogram_start([json.dumps(polygon)], self.retry)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 26, in wrapper
    return f(*args, **kw)
  File "/opt/app/apps/modeling/geoprocessing.py", line 146, in histogram_start
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 26, in wrapper
    return f(*args, **kw)
  File "/opt/app/apps/modeling/geoprocessing.py", line 76, in sjs_submit
    context_response = requests.post(geop_context_url, data='')
Exception: Unable to submit job to Spark JobServer.
Details = {
  "status": "ERROR",
  "result": "context geoprocessing not found"
}
```

Since new contexts can be created on Spark Job Server by sending a post request with a param and an empty body...

```sh
http POST :8090/contexts/geoprocessing body=""
```

...I'm going to add a guard in `sjs_submit` to create the context, then retry submitting the job if the context hasn't been found. Then I'll try to figure out why it occasionally may not be created/available in the first place.

**Comment by hectcastro** [comment]
> ...I'm going to add a guard in sjs_submit to create the context, then retry submitting the job if the context hasn't been found. Then I'll try to figure out why it occasionally may not be created/available in the first place.

It may be worth issuing this in the event of a missing `geoprocessing` context:

```bash
ubuntu@ip-10-0-3-70:~$ curl -v -XPUT "http://localhost:8090/contexts?reset=reboot"
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8090 (#0)
> PUT /contexts?reset=reboot HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:8090
> Accept: */*
> 
< HTTP/1.1 200 OK
* Server spray-can/1.3.3 is not blacklisted
< Server: spray-can/1.3.3
< Date: Wed, 28 Sep 2016 15:26:37 GMT
< Access-Control-Allow-Origin: *
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 2
< 
* Connection #0 to host localhost left intact
```

It claims to:

> kills all contexts and re-loads only the contexts from config

**Comment by kellyi** [comment]
Oh nice -- I'll take a look at that. I was looking through past occurrences of this and it seems like some of them have happened immediately following deployments to staging, but there are a couple others which recently happened on production. 

Initial thought was that the context wasn't getting created quickly enough for some reason, but if the context can just go missing somehow, probably better to reset the service altogether in case the missing context's just the sign of some other problem.
