### ISSUE TITLE
Exception: No slots available in Spark JobServer.
Details = {
  "status": "NO SLOTS AVAILABLE",
  "result": "Too many running jobs (8) for job context 'geoprocessing'"
}

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#1711]
View details in Rollbar: [https://rollbar.com/Azavea/MMW/items/183/](https://rollbar.com/Azavea/MMW/items/183/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "apps/modeling/tasks.py", line 77, in start_histogram_job
    'sjs_job_id': histogram_start([json.dumps(polygon)], self.retry)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 26, in wrapper
    return f(*args, **kw)
  File "apps/modeling/geoprocessing.py", line 174, in histogram_start
    return sjs_submit(host, port, args, data, retry)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 26, in wrapper
    return f(*args, **kw)
  File "apps/modeling/geoprocessing.py", line 78, in sjs_submit
    'Details = {}'.format(response.text)))
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 666, in retry
    raise exc
Exception: No slots available in Spark JobServer.
Details = {
  "status": "NO SLOTS AVAILABLE",
  "result": "Too many running jobs (8) for job context 'geoprocessing'"
}
```

**Comment by mmcfarland** [comment]
Closing this under the assumption that the s3 outage was the ultimate culprit.
