### ISSUE TITLE
Exception: No slots available in Spark JobServer.
Details = {
  "status": "NO SLOTS AVAILABLE",
  "result": "Too many running jobs (8) for job context 'geoprocessing'"
}

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#1712]
View details in Rollbar: [https://rollbar.com/Azavea/MMW/items/184/](https://rollbar.com/Azavea/MMW/items/184/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "apps/modeling/tasks.py", line 96, in start_histograms_job
    'sjs_job_id': histogram_start(json_polygons, self.retry)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 26, in wrapper
    return f(*args, **kw)
  File "apps/modeling/geoprocessing.py", line 174, in histogram_start
    return sjs_submit(host, port, args, data, retry)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 26, in wrapper
    return f(*args, **kw)
  File "apps/modeling/geoprocessing.py", line 78, in sjs_submit
    'Details = {}'.format(response.text)))
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 666, in retry
    raise exc
Exception: No slots available in Spark JobServer.
Details = {
  "status": "NO SLOTS AVAILABLE",
  "result": "Too many running jobs (8) for job context 'geoprocessing'"
}
```

**Comment by arottersman** [comment]
At the time of this error and the one in #1711, S3 was down. Here's some of the related discussion that went on in slack:

From Hector:
> The calls to S3 for the ingested GeoTrellis data are likely causing a bunch of problems.

From Terence:
> This may very well be a result of S3 being down. The geoprocessing jobs pull down tiles from S3, and without it they take longer, stay in the slots longer, and other waiting jobs give up.
>

**Comment by hectcastro** [comment]
I confirmed that there were a number of `java.net.SocketTimeoutException` entries for all of the Spark jobs. This led to backlog of jobs to build up and ultimately hit this queue size threshold.

**Comment by mmcfarland** [comment]
Closing this under the assumption that the s3 outage was the ultimate culprit.
