### ISSUE TITLE
Support date range filter for BiG CZ search

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#1855]
We need to figure out exactly how we want the date filter to work and how that translates to each data source API.

### CUAHSI

Neither Sites nor Services include date fields. As far as I can tell, there is no way to search on these by date.

The `GetSeriesCatalogForBox2` operation has `beginDate` and `endDate` params, but it throws an exception. I have tried many different date formats with no luck. This operation works fine on [water.sdsc.edu](water.sdsc.edu/hiscentral/webservices/hiscentral.asmx).

```
System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTime.ParseExact(String s, String format, IFormatProvider provider)
   at hiscentral.requestUrl(Double xmin, Double xmax, Double ymin, Double ymax, String conceptKeyword, String networkIDs, String beginDate, String endDate, Int32 nrows) in c:\inetpub\hiscentral.cuahsi.org\App_Code\hiscentral.cs:line 973
   at hiscentral.GetSeriesCatalogForBox3(Double xmin, Double xmax, Double ymin, Double ymax, String sampleMedium, String dataType, String valueType, String conceptKeyword, String networkIDs, String beginDate, String endDate) in c:\inetpub\hiscentral.cuahsi.org\App_Code\hiscentral.cs:line 724
```

### CINERGI

This endpoint supports `before` and `after` params. I think this filters resources by the `updated` field, but I'm not sure. Some of the search results I get are not consistent with this assumption. Resources have an `updated` field.

http://cinergi.sdsc.edu/geoportal/rest/find/document?searchText=diamond&after=2016-05-25&before=2016-06-30&f=pjson

### HydroShare

This endpoint supports `from_date` and `to_date` params, which filters resources by `date_created`. Resources have a `date_created` and `date_last_updated` field. 

https://www.hydroshare.org/hsapi/resource/?full_text_search=water&from_date=2015-08-30&to_date=2015-09-01

**Comment by kdeloach** [comment]
We discussed this and the conclusion is that the `created` date represents the date which observations are recorded, and this is the correct field to include in the date range filter.

**Comment by kdeloach** [comment]
Blocked until #1856 is complete and the CUAHSI API endpoint is fixed.

**Comment by kdeloach** [comment]
CINERGI CSW 3.0 has better support for date range filtering.

CUAHSI date range filter no longer throws an exception but the filter still doesn't working. This behavior is documented in #1945.

Closing.
