### ISSUE TITLE
Can't draw modification before initial TR-55 run completes

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#1901]
To reproduce:
* Draw AoI
* Site Storm Model
* While still polling current conditions, draw a land cover mod in a new scenario

![screen shot 2017-05-18 at 1 08 03 pm](https://cloud.githubusercontent.com/assets/7633670/26214670/3c32b550-3bcb-11e7-81a9-3a64690d25b8.png)

From `debugcelery.sh` output
```
[2017-05-18 13:04:31,677: ERROR/MainProcess] Task apps.modeling.tasks.run_tr55[758ef0ea-3f98-4512-845a-286d4250cd67] raised unexpected: Exception(u'Missing censuses for modifications',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app/apps/modeling/tasks.py", line 192, in run_tr55
    raise Exception('Missing censuses for modifications')
Exception: Missing censuses for modifications
[2017-05-18 13:04:31,695: ERROR/Worker-3] Task 758ef0ea-3f98-4512-845a-286d4250cd67 run from job 7627 raised exception: Missing censuses for modifications
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app/apps/modeling/tasks.py", line 192, in run_tr55
    raise Exception('Missing censuses for modifications')
Exception: Missing censuses for modifications
```

**Comment by rajadain** [comment]
See possibly related: https://rollbar.com/Azavea/MMW/items/194/

**Comment by mmcfarland** [comment]
May be indicated here as well: https://github.com/WikiWatershed/model-my-watershed/issues/1675
