### ISSUE TITLE
CINERGI timeouts on staging environment

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#1968]
CINERGI Geoportal requests timeout on staging. The same requests work fine from local development environments.

Here is the result of making a direct Geoportal request from a Python REPL from a staging app server EC2 instance on AWS.

```
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> r = requests.get('http://132.249.238.169:8080/geoportal/opensearch')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='132.249.238.169', port=8080): Max retries exceeded with url: /geoportal/opensearch (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe6cbac6450>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```

**Comment by hectcastro** [comment]
This is likely due to a lack of egress security group rules for port 8080.
