### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#2065]
View details in Rollbar: [https://rollbar.com/Azavea/MMW/items/206/](https://rollbar.com/Azavea/MMW/items/206/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "apps/modeling/tasks.py", line 300, in analyze_nlcd
    'coverage': float(histogram.get(nlcd, 0)) / total_count,
ZeroDivisionError: float division by zero
```

**Comment by mmcfarland** [comment]
In the above trace, `total_count` is `0`.  This occurs because the `result` argument to `analyze_nlcd` is being passed in as `{}`, meaning there are no counts of any type.  The `result` value is coming by way of `sjs_retrieve` and indicates a problem with the geoprocessing.

**Comment by mmcfarland** [comment]
We'll be making significant changes to the geoprocessing pipeline in the very near term.  If this bug is isolated and infrequent, we shouldn't spend the resources tracking it down before we replace the system.

**Comment by rajadain** [comment]
Getting a lot more notices for this now: https://rollbar.com/WikiWatershed/ModelMyWatershed/items/51/. Bringing in to higher priority.

**Comment by rajadain** [comment]
Again https://rollbar.com/WikiWatershed/ModelMyWatershed/items/271/
