### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2396]
View details in Rollbar: [https://rollbar.com/Azavea/MMW/items/233/](https://rollbar.com/Azavea/MMW/items/233/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "apps/geoprocessing_api/tasks.py", line 108, in analyze_nlcd
    'coverage': float(histogram.get(nlcd, 0)) / total_count,
ZeroDivisionError: float division by zero
```

**Comment by rajadain** [comment]
Still seeing this in staging and production, most recently with this shape:

```json
{"type":"MultiPolygon","coordinates":[[[[-72.86368302069604,41.551727491993255],[-72.86366692744195,41.55182785443572],[-72.8638922329992,41.55185997038439],[-72.86391369067132,41.551727491993255],[-72.86392441950738,41.55156289725028],[-72.86381713114679,41.55153881017957],[-72.86379567347467,41.55167931796553],[-72.86368302069604,41.551727491993255]]]]}
```

![image](https://user-images.githubusercontent.com/1430060/54619365-d4c8d180-4a3a-11e9-9a1d-c095e5656e5b.png)

https://rollbar.com/WikiWatershed/ModelMyWatershed/items/4/
https://rollbar.com/WikiWatershed/ModelMyWatershed/items/5/
https://rollbar.com/WikiWatershed/ModelMyWatershed/items/6/
https://rollbar.com/WikiWatershed/ModelMyWatershed/items/18/
https://rollbar.com/WikiWatershed/ModelMyWatershed/items/19/
https://rollbar.com/WikiWatershed/ModelMyWatershed/items/20/

**Comment by SRGDamia1** [comment]
I've gotten this several times with fairly large areas.  Most recently with the RWD results from a point on White Clay near Stroud (39.83583, -75.78194)

![image](https://user-images.githubusercontent.com/5374350/109992292-1eb72a80-7cd9-11eb-94cb-02265e4a3be9.png)

**Comment by rajadain** [comment]
The next time that happens, can you export the shape and include the geojson here? That would really help us add it as a test case. Thank you!

**Comment by SRGDamia1** [comment]
Here's the geojson for that exact point.  I think the issue must have something to do with irregularities on the edges of the geojson.  When I manually ran the RWD for the same point with a slightly higher simplification value (0.00015 instead of the default 0.0001) and then upload that geojson, the job succeeds.

Here's the polygon that fails:
[BCWC7_fails.txt](https://github.com/WikiWatershed/model-my-watershed/files/6086994/BCWC7_fails.txt)


Here's the polygon that works:
[BCWC7_polygon_drb.txt](https://github.com/WikiWatershed/model-my-watershed/files/6086982/BCWC7_polygon_drb.txt)

**Comment by SRGDamia1** [comment]
It's not just the land use that fails.  The soil, terrain, and water quality calls on the polygon also fail.
