### ISSUE TITLE
WebFault: Server raised fault: 'Unrecognized service. List of available method(s): GetSites GetSitesXml GetSiteInfo GetSiteInfoObject GetVariableInfo GetVariableInfoObject GetValues GetValuesObject'

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2414]
View details in Rollbar: [https://rollbar.com/Azavea/MMW/items/236/](https://rollbar.com/Azavea/MMW/items/236/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/opt/app/apps/bigcz/views.py", line 164, in details
    return Response(_get_details(request))
  File "/opt/app/apps/bigcz/views.py", line 116, in _get_details
    return details(**details_kwargs)
  File "/opt/app/apps/bigcz/clients/cuahsi/details.py", line 27, in details
    return wof.get_site_info(wsdl, site)
  File "/usr/local/lib/python2.7/dist-packages/ulmo/cuahsi/wof/core.py", line 99, in get_site_info
    response = suds_client.service.GetSiteInfo(site_code)
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 521, in __call__
    return client.invoke(args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 581, in invoke
    result = self.send(soapenv)
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 621, in send
    original_soapenv=original_soapenv)
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 670, in process_reply
    raise WebFault(fault, replyroot)
WebFault: Server raised fault: 'Unrecognized service. List of available method(s): GetSites GetSitesXml GetSiteInfo GetSiteInfoObject GetVariableInfo GetVariableInfoObject GetValues GetValuesObject'
```

**Comment by rajadain** [comment]
Possibly same treatment as #2413. It may be a good idea to track how often we encounter these exceptions for feedback for Ulmo development, but not sure we have the infrastructure for that (Rollbar maybe?)
