### ISSUE TITLE
Catchment intersection divides by 0

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#2472]
View details in Rollbar: [https://rollbar.com/Azavea/MMW/items/244/](https://rollbar.com/Azavea/MMW/items/244/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "apps/geoprocessing_api/tasks.py", line 98, in analyze_catchment_water_quality
    return {'survey': catchment_water_quality(area_of_interest)}
  File "apps/geoprocessing_api/calcs.py", line 145, in catchment_water_quality
    r['geom'])]
  File "apps/geoprocessing_api/calcs.py", line 195, in catchment_intersects_aoi
    reprojected_catchment.area) * 100)
ZeroDivisionError: float division by zero
```

**Comment by mmcfarland** [comment]
Looks like a catchment was produced with no size

| | |
| ---|---|
| catchment | {"coordinates": [],"type": "MultiPolygon"} |
| catchment_geom | <class 'django.contrib.gis.geos.collections.MultiPolygon'>|
| intersection_area | 0|

**Comment by mmcfarland** [comment]
The AoI which produced the query for these catchments is:

Middle Delaware-Mongaup-Brodhead, HUC-8 Subbasin

**Comment by kellyi** [comment]
Ok, this is happening because the PostGIS query we use to simplify the geometry reduces this AOI to an empty list:

```sql
ST_AsGeoJSON(ST_Simplify(geom, 0.0003)) as geom
```

->

```python
{u'type': u'MultiPolygon', u'coordinates': [[[[-74.6550994735584, 41.3966510841167], [-74.6547470077423, 41.396591391265], [-74.6548275328687, 41.3963301092979], [-74.6551799974458, 41.3963898019133], [-74.6550994735584, 41.3966510841167]]], [[[-74.6550994735584, 41.3966510841167], [-74.6554519399717, 41.3967107760028], [-74.6553714167261, 41.3969720584574], [-74.6550189490737, 41.396912366335], [-74.6550994735584, 41.3966510841167]]], [[[-74.6553714167261, 41.3969720584574], [-74.6557238849758, 41.3970317496142], [-74.6556433623719, 41.3972930323199], [-74.6552908928832, 41.3972333409268], [-74.6553714167261, 41.3969720584574]]], [[[-74.6556433623719, 41.3972930323199], [-74.6559958324579, 41.3973527227473], [-74.6559153104958, 41.3976140057043], [-74.6555628391707, 41.3975543150405], [-74.6556433623719, 41.3972930323199]]], [[[-74.6559153104958, 41.3976140057043], [-74.6573252017691, 41.3978527587026], [-74.657244684166, 41.3981140426197], [-74.6558347879364, 41.397875288676], [-74.6559153104958, 41.3976140057043]]], [[[-74.657244684166, 41.3981140426197], [-74.6575971597167, 41.3981737286914], [-74.6576776760807, 41.397912444538], [-74.6580301509894, 41.3979721294078], [-74.6579496358645, 41.3982334137974], [-74.6583021126097, 41.3982930979378], [-74.6582215981266, 41.3985543825787], [-74.6578691201424, 41.398494698202], [-74.6571641659656, 41.3983753265516], [-74.657244684166, 41.3981140426197]]]]}
```

**Comment by kellyi** [comment]
7870 has an area of 1.080 ha. I tried out this query on other similarly small wq catchments (7225, 7235, 7310, 7727, 7923) but wasn't able to return an empty list:

```sql
SELECT ST_AsGeoJSON(ST_Simplify(geom, 0.0003)) as geom
FROM drb_catchment_water_quality WHERE nord=7870;
```

**Comment by kellyi** [comment]
Ran

```
SELECT nord, ST_AsGeoJSON(ST_Simplify(geom, 0.0003)) as geom
FROM drb_catchment_water_quality;
```

then exported it & grepped for the empty coordinates list and 7870 was the only one returned:

```sh
$ cat res.csv | grep '\[\]'
7870,"{""type"":""MultiPolygon"",""coordinates"":[]}"
```

Since this affects only one catchment, I'm just going to add a guard against catchment area being 0 prior to the division op.
