### ISSUE TITLE
ValueError: need more than 0 values to unpack

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2735]
View details in Rollbar: [https://rollbar.com/Azavea/MMW/items/289/](https://rollbar.com/Azavea/MMW/items/289/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "apps/geoprocessing_api/tasks.py", line 279, in analyze_terrain
    [elevation, slope] = result
ValueError: need more than 0 values to unpack
```

**Comment by rajadain** [comment]
Just got the 100th error for this. Seeing it consistently since last release.

**Comment by rajadain** [comment]
Also here: https://rollbar.com/WikiWatershed/ModelMyWatershed/items/205/

**Comment by rajadain** [comment]
Seems to be upticking in the last two weeks

<img width="1325" height="285" alt="Image" src="https://github.com/user-attachments/assets/e7f5dc4e-fac1-46d2-b7ac-1e904438dc5c" />
