### ISSUE TITLE
EnviroDIY WDC result fails

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2807]
To replicate:
- Search for "water" in Monitor on the lower Schuylkill HUC
- CLick on first CUAHSI result, "EnviroDIY SHPK3S Pickering Creek Eastern Trib at Bryn Coed Lane"

![screen shot 2018-04-26 at 5 01 16 pm](https://user-images.githubusercontent.com/12868342/39331891-bdff5e2e-4973-11e8-8ab0-a84570930b55.png)

**Comment by rajadain** [comment]
Also see https://rollbar.com/Azavea/MMW/items/318/

**Comment by rajadain** [comment]
Also see https://rollbar.com/Azavea/MMW/items/309/ and https://rollbar.com/Azavea/MMW/items/310/

**Comment by caseycesari** [comment]
Graceful failure though! 👏

**Comment by rajadain** [comment]
The latest error is happening at this line in Ulmo:

https://github.com/ulmo-dev/ulmo/blob/ba6ee72d91057c43d356e901a9ce511e1be16684/ulmo/util/misc.py#L52

```
Internal Server Error: /bigcz/values
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/opt/app/apps/bigcz/views.py", line 170, in values
    return Response(_get_values(request))
  File "/opt/app/apps/bigcz/views.py", line 150, in _get_values
    return values(**values_kwargs)
  File "/opt/app/apps/bigcz/clients/cuahsi/details.py", line 55, in values
    return wof.get_values(wsdl, site, variable, from_date, to_date, None)
  File "/usr/local/lib/python2.7/dist-packages/ulmo/cuahsi/wof/core.py", line 170, in get_values
    start_datetime = util.convert_datetime(start)
  File "/usr/local/lib/python2.7/dist-packages/ulmo/util/misc.py", line 52, in convert_datetime
    return pandas.Timestamp(datetime).to_datetime()
AttributeError: 'Timestamp' object has no attribute 'to_datetime'
```

because `Timestamp().to_datetime` was [deprecated in 0.21](https://pandas.pydata.org/pandas-docs/version/0.21/generated/pandas.Timestamp.to_datetime.html) and [removed in 0.23](https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.Timestamp.to_pydatetime.html#pandas.Timestamp.to_pydatetime).

Since Ulmo [does not specify dependency versions](https://github.com/emiliom/ulmo/blob/22951dc3f52e30f8596bf27950a0138d3f6f2103/requirements.txt#L8), the  latest version of Pandas is used, causing this error.

It would be great to get this fixed on the Ulmo end /cc @emiliom @aufdenkampe 

In the interim I'll see if Pandas can be pinned to an older version that still has `.to_datetime` support.

**Comment by rajadain** [comment]
0.23 was released [two weeks ago](https://pypi.org/project/pandas/0.23.0/#history), and this wasn't caught as a separate bug because it was masked by the original issues.

**Comment by rajadain** [comment]
Even though the specific issues around EnviroDIY have been found and fixed so far, there remain problems with it on staging (see #2859). The good news is that the others (especially NWIS values) seem to be working faster than ever before. Accessing EnviroDIY crashes the server though, so I would recommend not testing with it until we've fixed the issue (or added exception handling for it).
