### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2819]
View details in Rollbar: [https://rollbar.com/Azavea/MMW/items/313/](https://rollbar.com/Azavea/MMW/items/313/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 26, in wrapper
    return f(*args, **kw)
  File "apps/modeling/tasks.py", line 370, in run_subbasin_gwlfe_chunks
    for watershed_id in watershed_ids
  File "/usr/local/lib/python2.7/dist-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 630, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 380, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 26, in wrapper
    return f(*args, **kw)
  File "apps/modeling/tasks.py", line 344, in run_gwlfe
    output = to_gms_file(model_input)
  File "apps/modeling/tasks.py", line 436, in to_gms_file
    writer.write(pre_z)
  File "/usr/local/lib/python2.7/dist-packages/gwlfe/parser.py", line 2052, in write
    z.Temp[year][month][day],
IndexError: list index out of range
```

**Comment by rajadain** [comment]
Shares points with #2826
