### ISSUE TITLE
Celery / Geoprocessing Timeout in Production

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2981]
![image](https://user-images.githubusercontent.com/1430060/46029080-6bd25380-c0c0-11e8-9d74-abdbdf3ba3ed.png)

RWD is not finishing either. Potentially same as #2695.

**Comment by rajadain** [comment]
Final log entries in one of the Celery worker logs are these:

```
[2018-09-11 12:52:18,179: WARNING/ForkPoolWorker-2] GEOS_NOTICE: Self-intersection at or near point 1685624.9999999939 2116694.9999999921
[2018-09-11 12:53:15,377: ERROR/MainProcess] Task 20233ab0-4286-4cf1-a295-d976ee6dfd85 run from job 1017094 raised exception: TimeLimitExceeded(300.0,)
None
[2018-09-11 12:53:15,552: ERROR/MainProcess] Failed to save job error status. Job will appear hung.                      Job Id: 1017094
[2018-09-11 12:53:15,552: ERROR/MainProcess] Pool callback raised exception: AttributeError("'IntegrityError' object has no attribute 'errno'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 1747, in safe_apply_callback
    fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/request.py", line 366, in on_failure
    self.id, exc, request=self, store_result=self.store_errors,
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 168, in mark_as_failure
    self._call_task_errbacks(request, exc, traceback)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 175, in _call_task_errbacks
    errback(request, exc, traceback)
  File "/usr/local/lib/python2.7/dist-packages/celery/canvas.py", line 178, in __call__
    return self.type(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 630, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 380, in __call__
    return self.run(*args, **kwargs)
  File "apps/core/tasks.py", line 43, in save_job_error
    .format(e.errno, e.strerror))
AttributeError: 'IntegrityError' object has no attribute 'errno'
[2018-09-11 12:53:15,552: ERROR/MainProcess] Hard time limit (300.0s) exceeded for apps.geoprocessing_api.tasks.analyze_catchment_water_quality[20233ab0-4286-4cf1-a295-d976ee6dfd85]
[2018-09-11 12:53:15,554: ERROR/MainProcess] Task 20233ab0-4286-4cf1-a295-d976ee6dfd85 run from job 1017094 raised exception: TimeLimitExceeded(300.0,)
None
[2018-09-11 12:53:15,637: ERROR/MainProcess] Failed to save job error status. Job will appear hung.                      Job Id: 1017094
[2018-09-11 12:53:15,638: ERROR/MainProcess] Pool callback raised exception: AttributeError("'IntegrityError' object has no attribute 'errno'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 1747, in safe_apply_callback
    fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/request.py", line 314, in on_timeout
    self.id, exc, request=self, store_result=self.store_errors,
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 168, in mark_as_failure
    self._call_task_errbacks(request, exc, traceback)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 175, in _call_task_errbacks
    errback(request, exc, traceback)
  File "/usr/local/lib/python2.7/dist-packages/celery/canvas.py", line 178, in __call__
    return self.type(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 630, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 380, in __call__
    return self.run(*args, **kwargs)
  File "apps/core/tasks.py", line 43, in save_job_error
    .format(e.errno, e.strerror))
AttributeError: 'IntegrityError' object has no attribute 'errno'
[2018-09-11 12:53:15,750: ERROR/MainProcess] Process 'ForkPoolWorker-2' pid:32332 exited with 'signal 9 (SIGKILL)'
```

It seems as if saving errors failed a couple times, and that led to the process being killed. However, if I check the service status, that reports that the processes are up:

```
$ sudo service celeryd status
celery init v10.1.
Using config script: /etc/default/celeryd
celeryd (node Blue-worker0) (pid 1481) is up...
celeryd (node Blue-worker1) (pid 1506) is up...
```

I'm going to try and restart the service and see if it helps.

**Comment by rajadain** [comment]
Doing so has started processing all the queue up jobs.

**Comment by rajadain** [comment]
Restarting `celeryd` fixed it.

I believe the main symptom of the problem is that the workers exit abruptly

> Process 'ForkPoolWorker-2' pid:32332 exited with 'signal 9 (SIGKILL)'

but either don't restart themselves (and are still reported up by the `celeryd` service), or do restart themselves (and are reported up correctly by `celeryd`) but fail to attach to the main process and do not pick up tasks.

I wonder if there is a way we could monitor logs for the `SIGKILL` line and restart the `celeryd` service in response? Seems like a hack, but the best I can think of at the moment.

**Comment by mmcfarland** [comment]
Interesting.  This was likely initiated by the redis node failure that happened over the weekend.  Perhaps while it was failing over to the backup node, the connections timed out and entered this error state.
