### ISSUE TITLE
Investigate Monitor Failures

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3063]
CUAHSI detail and CINERGI list endpoints are failing. Investigate.

**Comment by rajadain** [comment]
This is the error we're seeing for CUAHSI Values:

```
Internal Server Error: /bigcz/values
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/opt/app/apps/bigcz/views.py", line 173, in values
    return Response(_get_values(request))
  File "/opt/app/apps/bigcz/views.py", line 153, in _get_values
    return values(**values_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/timeout_decorator/timeout_decorator.py", line 81, in new_function
    return function(*args, **kwargs)
  File "/opt/app/apps/bigcz/clients/cuahsi/details.py", line 70, in values
    return wof.get_values(wsdl, site, variable, from_date, to_date, None)
  File "/usr/local/lib/python2.7/dist-packages/ulmo/cuahsi/wof/core.py", line 179, in get_values
    endDate=end_dt_isostr)
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 566, in __call__
    return client.invoke(args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 705, in invoke
    result = self.send(soapenv)
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 752, in send
    return self.process_reply(content, e.httpcode, tostr(e))
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 814, in process_reply
    raise WebFault(fault, replyroot)
WebFault: Server raised fault: 'System.Web.Services.Protocols.SoapException: Value cannot be null.
Parameter name: s
   at WaterOneFlow.odws.v1_1.Service.GetValuesObject(String location, String variable, String startDate, String endDate, String authToken)
   at WaterOneFlow.odws.v1_1.Service.GetValues(String location, String variable, String startDate, String endDate, String authToken)'
```

I tried this in SoapUI, and got the same output for similar input:

```xml
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:ws="http://www.cuahsi.org/his/1.1/ws/">
   <soap:Header/>
   <soap:Body>
      <ws:GetValues>
         <!--Optional:-->
         <ws:location>NWISUV:01474500</ws:location>
         <!--Optional:-->
         <ws:variable>NWISUV:72204</ws:variable>
         <!--Optional:-->
         <ws:startDate>11/14/2018</ws:startDate>
         <!--Optional:-->
         <ws:endDate>12/14/2018</ws:endDate>
      </ws:GetValues>
   </soap:Body>
</soap:Envelope>
```
```xml
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
   <env:Header xmlns:env="http://www.w3.org/2003/05/soap-envelope">
      <wsa:Action>http://schemas.xmlsoap.org/ws/2004/08/addressing/fault</wsa:Action>
      <wsa:MessageID>urn:uuid:6b4bfc33-7fbb-4589-b06b-557716c07444</wsa:MessageID>
      <wsa:RelatesTo>urn:uuid:06718663-10e0-4d3e-a91f-c788adc83bad</wsa:RelatesTo>
      <wsa:To>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</wsa:To>
      <wsse:Security>
         <wsu:Timestamp wsu:Id="Timestamp-dc7b3c1b-229a-45b9-b8a9-428a7afb2a61">
            <wsu:Created>2018-12-18T20:39:25Z</wsu:Created>
            <wsu:Expires>2018-12-18T20:44:25Z</wsu:Expires>
         </wsu:Timestamp>
      </wsse:Security>
   </env:Header>
   <soap:Body>
      <soap:Fault>
         <soap:Code>
            <soap:Value>soap:Receiver</soap:Value>
         </soap:Code>
         <soap:Reason>
            <soap:Text xml:lang="en">System.Web.Services.Protocols.SoapException: Value cannot be null.
Parameter name: s
   at WaterOneFlow.odws.v1_1.Service.GetValuesObject(String location, String variable, String startDate, String endDate, String authToken)
   at WaterOneFlow.odws.v1_1.Service.GetValues(String location, String variable, String startDate, String endDate, String authToken)</soap:Text>
         </soap:Reason>
         <soap:Detail/>
      </soap:Fault>
   </soap:Body>
</soap:Envelope>
```

I don't remember `authToken` being there before, so maybe Ulmo needs to be updated to account for it?

**Comment by rajadain** [comment]
For CINERGI, this endpoint that used to work: http://cinergi.sdsc.edu/geoportal/opensearch?q=water&size=100&from=1&f=json&bbox=-75.2585830259,39.8760546985,-75.1597594229,40.0310812816 now does not, and instead responds with:

```json
{
  "error": "Search error: {\"error\":{\"root_cause\":[{\"type\":\"parse_exception\",\"reason\":\"geo coordinates must be numbers\"}],\"type\":\"parse_exception\",\"reason\":\"geo coordinates must be numbers\"},\"status\":400}"
}
```

<details>
<summary>

```
$ http --print HhBb cinergi.sdsc.edu/geoportal/opensearch q==water size==100 from==1 bbox=="-75.2585830259,39.8760546985,-75.1597594229,40.0310812816" f==json
```
</summary>

```http
GET /geoportal/opensearch?q=water&size=100&from=1&bbox=-75.2585830259%2C39.8760546985%2C-75.1597594229%2C40.0310812816&f=json HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: cinergi.sdsc.edu
User-Agent: HTTPie/1.0.2



HTTP/1.1 500
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Headers: Authorization
Access-Control-Allow-Headers: X-Requested-With
Access-Control-Allow-Origin: *
Access-Control-Allow-Origin: : *
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Length: 225
Content-Type: application/json;charset=UTF-8
Date: Tue, 18 Dec 2018 21:07:20 GMT
Expires: 0
Pragma: no-cache
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: ARR/3.0
X-Powered-By: ASP.NET
X-XSS-Protection: 1; mode=block

{
    "error": "Search error: {\"error\":{\"root_cause\":[{\"type\":\"parse_exception\",\"reason\":\"geo coordinates must be numbers\"}],\"type\":\"parse_exception\",\"reason\":\"geo coordinates must be numbers\"},\"status\":400}"
}
```
</details>

**Comment by rajadain** [comment]
Both these issues stem from changes on the third party ends, not on our end.

**Comment by emiliom** [comment]
I've started to follow up on the CUAHSI GetValues ("details") issue. For now, I just want to note that the problem does not impact every single site returned by the CUAHSI WDC catalog; it's a bit narrower, limited apparently to USGS NWIS stations -- though those stations typically represent the majority of stations in any given area.

Stations from most, possibly all, smaller networks, including EnviroDIY and several CUAHSI-hosted networks I've tested, are not affected.

**Comment by emiliom** [comment]
The CUAHSI GetValues / details issue has been fixed, at least for USGS NWIS.

**Comment by rajadain** [comment]
Hi @emiliom, we just got this error for an NWIS request again, it asked for `authToken` in a single instance:

![image](https://user-images.githubusercontent.com/1430060/53748941-56820200-3e74-11e9-8afa-ab5dce7c0b1a.png)

This was using the WSDL from http://hydroportal.cuahsi.org/nwisdv/cuahsi_1_1.asmx?WSDL and the parameters of:


  | values arguments
-- | --
"wsdl" | "http://hydroportal.cuahsi.org/nwisdv/cuahsi_1_1.asmx?WSDL="
"site" | "NWISDV:04174500"
"variable" | "NWISDV:00095/DataType=MINIMUM"
"from_date" | "09/30/2012"
"to_date" | "09/30/2013"

We cannot replicate this in MMW just yet, but are seeing it in SoapUI. 

The trace we're getting is:

```
WebFault:

Server raised fault: 'System.Web.Services.Protocols.SoapException: Value cannot be null.
Parameter name: s
   at WaterOneFlow.odws.v1_1.Service.GetValuesObject(String location, String variable, String startDate, String endDate, String authToken) in c:\inetpub\wwwroot\NWISDV\App_Code\Service_1_1.cs:line 280
   at WaterOneFlow.odws.v1_1.Service.GetValues(String location, String variable, String startDate, String endDate, String authToken) in c:\inetpub\wwwroot\NWISDV\App_Code\Service_1_1.cs:line 195'
```

I'll let you know if it happens again or consistently. Just a heads up for now.

**Comment by emiliom** [comment]
Thanks for the heads up. Let me know if it happens again, repeatedly.
