### ISSUE TITLE
OSError: [Errno 17] File exists: '/var/lib/mmw/.local/share/ulmo'

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3073]
View details in Rollbar: [https://rollbar.com/Azavea/MMW/items/346/](https://rollbar.com/Azavea/MMW/items/346/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/opt/app/apps/bigcz/views.py", line 173, in values
    return Response(_get_values(request))
  File "/opt/app/apps/bigcz/views.py", line 153, in _get_values
    return values(**values_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/timeout_decorator/timeout_decorator.py", line 81, in new_function
    return function(*args, **kwargs)
  File "/opt/app/apps/bigcz/clients/cuahsi/details.py", line 69, in values
    from ulmo.cuahsi import wof
  File "/usr/local/lib/python2.7/dist-packages/ulmo/__init__.py", line 13, in <module>
    from . import cpc
  File "/usr/local/lib/python2.7/dist-packages/ulmo/cpc/__init__.py", line 1, in <module>
    from . import drought
  File "/usr/local/lib/python2.7/dist-packages/ulmo/cpc/drought/__init__.py", line 8, in <module>
    from .core import get_data
  File "/usr/local/lib/python2.7/dist-packages/ulmo/cpc/drought/core.py", line 26, in <module>
    CPC_DROUGHT_DIR = os.path.join(util.get_ulmo_dir(), 'cpc/drought')
  File "/usr/local/lib/python2.7/dist-packages/ulmo/util/misc.py", line 107, in get_ulmo_dir
    mkdir_if_doesnt_exist(return_dir)
  File "/usr/local/lib/python2.7/dist-packages/ulmo/util/misc.py", line 114, in mkdir_if_doesnt_exist
    os.makedirs(dir_path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/var/lib/mmw/.local/share/ulmo'
```

**Comment by rajadain** [comment]
This seems vaguely familiar but I can't find an existing issue that talks about it, neither here nor in https://github.com/ulmo-dev/ulmo/issues/
