### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3096]
## Exception: [nlcd_soil] Geoprocessing Error.Details: java.lang.ArrayIndexOutOfBoundsException: 5

View details in Rollbar: [https://rollbar.com/WikiWatershed/ModelMyWatershed/items/8/](https://rollbar.com/WikiWatershed/ModelMyWatershed/items/8/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "apps/modeling/tasks.py", line 208, in nlcd_soil
    raise Exception('[nlcd_soil] {}'.format(result['error']))
Exception: [nlcd_soil] Geoprocessing Error.
Details: com.vividsolutions.jts.geom.TopologyException: found non-noded intersection between LINESTRING ( -2245402.472382275 1830864.629855696, -2245402.472382272 1830864.6298557061 ) and LINESTRING ( -2245402.472382275 1830864.6298556959, -2245402.472373349 1830864.629892373 ) [ (-2245402.4723822745, 1830864.6298556977, NaN) ]
```

**Comment by rajadain** [comment]
I tried to find out which shape triggered this, by pulling rows from `core_job` that were within 10 minutes of this exception:

```sql
SELECT uuid, model_input, created_at, error, status, user_id
FROM core_job
WHERE created_at BETWEEN (timestamp '2019-03-14 15:46:05.919447+00' - interval '5 minutes')
                     AND (timestamp '2019-03-14 15:46:05.919447+00' + interval '5 minutes')
ORDER BY created_at;
```

The result was this file: [intersecting-shape-investigation.zip](https://github.com/WikiWatershed/model-my-watershed/files/2984847/intersecting-shape-investigation.zip)

I tried out all the shapes found in the triggering rows, and could not reproduce the failure in any of them. They all succeeded:

![image](https://user-images.githubusercontent.com/1430060/54630364-039d7280-4a50-11e9-9eb1-c786ef6bd925.png)

![image](https://user-images.githubusercontent.com/1430060/54630370-07c99000-4a50-11e9-9751-f4e89d83df02.png)

![image](https://user-images.githubusercontent.com/1430060/54630374-0b5d1700-4a50-11e9-83a1-ed0c0a93f7aa.png)

![image](https://user-images.githubusercontent.com/1430060/54630381-0ef09e00-4a50-11e9-9cfa-6f7ea103ab03.png)

![image](https://user-images.githubusercontent.com/1430060/54630386-131cbb80-4a50-11e9-87f7-6c432d4239eb.png)

All of these shapes can be found in: [failing-intersecting-shapes.zip](https://github.com/WikiWatershed/model-my-watershed/files/2984855/failing-intersecting-shapes.zip)

Since this cannot be reproduced, I'm closing this issue for now.
