### ISSUE TITLE
Exception: Missing censuses for modifications

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3097]
View details in Rollbar: [https://rollbar.com/WikiWatershed/ModelMyWatershed/items/9/](https://rollbar.com/WikiWatershed/ModelMyWatershed/items/9/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "apps/modeling/tasks.py", line 283, in run_tr55
    raise Exception('Missing censuses for modifications')
Exception: Missing censuses for modifications
```

**Comment by rajadain** [comment]
Seen again https://rollbar.com/WikiWatershed/ModelMyWatershed/items/207
