### ISSUE TITLE
Exception: SRAT Catchment API request failed: 502 {"message": "Internal server error"}

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3161]
View details in Rollbar: [https://rollbar.com/WikiWatershed/ModelMyWatershed/items/44/](https://rollbar.com/WikiWatershed/ModelMyWatershed/items/44/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "apps/modeling/tasks.py", line 392, in run_srat
    (r.status_code, r.text))
Exception: SRAT Catchment API request failed: 502 {"message": "Internal server error"}
```

**Comment by rajadain** [comment]
This error was seen for this project: https://staging.modelmywatershed.org/project/1432/scenario/2542

Which is using the [Salt River below Saguaro Lake, HUC-10 Watershed (ID 1506010603)](https://github.com/WikiWatershed/model-my-watershed/files/3556293/Salt.River.below.Saguaro.Lake.HUC-10.Watershed.ID.1506010603.geojson.txt) area of interest, centered around Phoenix AZ:

![image](https://user-images.githubusercontent.com/1430060/63953711-d964cd80-ca4f-11e9-989e-bafec90088c3.png)

The full SRAT API interaction is captured here: [salt-river-below-saguaro-lake-huc10-srat-interaction.txt](https://github.com/WikiWatershed/model-my-watershed/files/3556297/salt-river-below-saguaro-lake-huc10-srat-interaction.txt)

Mainly, the error we're getting back is:

```http
HTTP/1.1 400 Bad Request
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 166
Content-Type: application/json
Date: Thu, 29 Aug 2019 15:21:00 GMT
X-Amzn-Trace-Id: Root=1-5d67ed5c-3751031994400cf8df28f1b0;Sampled=0
x-amz-apigw-id: fMIGhHw7CYcFvWA=
x-amzn-RequestId: 9bbaa942-ca70-11e9-ac02-37c31465dd89

Additional properties are not allowed ('150601060306', '150601060304', '150601060303', '150601060307', '150601060305', '150601060301', '150601060302' were unexpected)
```

This is likely because the SRAT API only supports areas limited to the Delaware River Basin. If that is the case, this card can be closed. If that is not the case, the issue is likely on the SRAT end. I will inform our colleagues that maintain it and report my findings here.
