### ISSUE TITLE
Fix JavaScript Tests in CI

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3230]
Currently failing with:

```
+ [[ -z '' ]]
+ vagrant ssh app -c 'cd /var/www/mmw/static &&
        xvfb-run /opt/app/node_modules/.bin/testem -f /opt/app/testem.json ci '

/opt/app/node_modules/testem/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/opt/app/node_modules/testem/node_modules/socket.io/lib/store.js:35:42)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/app/node_modules/testem/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
Build step 'Execute shell' marked build as failure
```

http://civicci01.internal.azavea.com/view/mmw/job/model-my-watershed-pull-requests/4142/console

**Comment by rajadain** [comment]
Fixed for `pull-requests`. Steps were:

* `ssh` in to `civicci01`
* `sudo su jenkins`
* `cd /var/lib/jenkins/workspace/model-my-watershed-pull-requests/`
* `rm -rf src/mmw/node_modules`
* `vagrant up app`
* `./scripts/yarn.sh`
* `vagrant halt`

After that I retried the PR builder and it ran tests successfully.
