### ISSUE TITLE
Resolve Celery Worker Failures

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3277]
Recently we've seen the following logs in production:

```
[2020-03-29 14:02:12,986: INFO/MainProcess] Received task: apps.modeling.geoprocessing.run[9fbb61d6-b843-
4c02-a1f0-a2d9a623472c]
[2020-03-29 14:02:28,099: INFO/MainProcess] Received task: apps.geoprocessing_api.tasks.analyze_catchment
_water_quality[0fc85ff3-427e-44e3-8e0c-d245aadda8d6]
[2020-03-29 14:02:29,550: INFO/MainProcess] Received task: apps.modeling.geoprocessing.run[f95bac4e-7ad2-
4f0a-829b-fbe2ef4956c4]
[2020-03-29 14:02:54,965: INFO/MainProcess] Received task: apps.geoprocessing_api.tasks.analyze_protected
_lands[8d9ebea7-3bf8-4594-b65e-707bfd6b6f6a]
[2020-03-29 14:02:58,973: INFO/MainProcess] Received task: apps.geoprocessing_api.tasks.analyze_climate[e
e0ed10d-847a-4fbb-97a5-26bc493ecaf8]
[2020-03-29 14:03:08,994: INFO/MainProcess] Received task: apps.geoprocessing_api.tasks.analyze_nlcd[cb18
e93a-c042-416a-9606-441807b9f912]
[2020-03-29 14:04:51,399: WARNING/ForkPoolWorker-1] GEOS_NOTICE: Self-intersection at or near point 16856
24.9999999939 2116694.9999999921
[2020-03-29 14:05:53,012: WARNING/ForkPoolWorker-1] GEOS_NOTICE: Self-intersection at or near point 17955
15.0000000012 2076375.0000000005
[2020-03-29 14:08:08,887: ERROR/MainProcess] Task 0fc85ff3-427e-44e3-8e0c-d245aadda8d6 run from job 27487
14 raised exception: TimeLimitExceeded(300.0,)
None
[2020-03-29 14:08:09,056: ERROR/MainProcess] Task handler raised error: TimeLimitExceeded(300.0,)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 658, in on_hard_timeout
    raise TimeLimitExceeded(job._timeout)
TimeLimitExceeded: TimeLimitExceeded(300.0,)
[2020-03-29 14:08:09,058: ERROR/MainProcess] Hard time limit (300.0s) exceeded for apps.geoprocessing_api
.tasks.analyze_catchment_water_quality[0fc85ff3-427e-44e3-8e0c-d245aadda8d6]
[2020-03-29 14:08:09,059: ERROR/MainProcess] Task 0fc85ff3-427e-44e3-8e0c-d245aadda8d6 run from job 27487
14 raised exception: TimeLimitExceeded(300.0,)
None
[2020-03-29 14:08:09,264: ERROR/MainProcess] Process 'ForkPoolWorker-1' pid:2587 exited with 'signal 9 (SIGKILL)'
[2020-03-30 12:48:47,226: WARNING/MainProcess] Restoring 4 unacknowledged message(s)
[2020-03-30 12:48:58,163: INFO/MainProcess] Connected to redis://cache.service.mmw.internal:6379/2
[2020-03-30 12:48:58,176: INFO/MainProcess] mingle: searching for neighbors
[2020-03-30 12:48:59,203: INFO/MainProcess] mingle: all alone
```
```
[2020-03-11 11:59:20,327: INFO/MainProcess] Received task: apps.modeling.geoprocessing.run[e382dcf5-c88b-
459e-ab09-0c38ca48f09a]
[2020-03-11 11:59:20,398: INFO/MainProcess] Received task: apps.modeling.geoprocessing.multi[b9a323ba-d70
4-4386-bc8d-b887b32837ec]
[2020-03-11 12:02:31,712: WARNING/ForkPoolWorker-1] GEOS_NOTICE: Self-intersection at or near point 16856
24.9999999939 2116694.9999999921
[2020-03-11 12:03:41,621: WARNING/ForkPoolWorker-1] GEOS_NOTICE: Self-intersection at or near point 17955
15.0000000012 2076375.0000000005
[2020-03-11 12:04:19,232: ERROR/MainProcess] Task 35cd844a-71e3-432a-ae57-edb3677ebbff run from job 27159
16 raised exception: TimeLimitExceeded(300.0,)
None
[2020-03-11 12:04:19,437: ERROR/MainProcess] Task handler raised error: TimeLimitExceeded(300.0,)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 658, in on_hard_timeout
    raise TimeLimitExceeded(job._timeout)
TimeLimitExceeded: TimeLimitExceeded(300.0,)
[2020-03-11 12:04:19,438: ERROR/MainProcess] Hard time limit (300.0s) exceeded for apps.geoprocessing_api
.tasks.analyze_catchment_water_quality[35cd844a-71e3-432a-ae57-edb3677ebbff]
[2020-03-11 12:04:19,439: ERROR/MainProcess] Task 35cd844a-71e3-432a-ae57-edb3677ebbff run from job 27159
16 raised exception: TimeLimitExceeded(300.0,)
None
[2020-03-11 12:04:19,650: ERROR/MainProcess] Process 'ForkPoolWorker-1' pid:2588 exited with 'signal 9 (S
IGKILL)'
[2020-03-30 12:48:47,229: WARNING/MainProcess] Restoring 4 unacknowledged message(s)
[2020-03-30 12:48:58,868: INFO/MainProcess] Connected to redis://cache.service.mmw.internal:6379/2
[2020-03-30 12:48:58,876: INFO/MainProcess] mingle: searching for neighbors
[2020-03-30 12:48:59,911: INFO/MainProcess] mingle: all alone
```
```
[2020-03-26 13:41:09,032: INFO/MainProcess] Received task: apps.geoprocessing_api.tasks.analyze_protected
_lands[749c7502-46c0-4bd7-9c09-9c3a44a48005]
[2020-03-26 13:41:09,234: INFO/MainProcess] Received task: apps.geoprocessing_api.tasks.analyze_nlcd[b587
51eb-31a9-4800-820d-5ec1a41508ca]
[2020-03-26 13:41:40,114: WARNING/ForkPoolWorker-1] GEOS_NOTICE: Self-intersection at or near point 17955
15.0000000012 2076375.0000000005
[2020-03-26 13:46:09,101: ERROR/MainProcess] Task 99bec67c-0056-44a6-8a33-bf45746a91d5 run from job 27439
26 raised exception: TimeLimitExceeded(300.0,)
None
[2020-03-26 13:46:09,269: ERROR/MainProcess] Task handler raised error: TimeLimitExceeded(300.0,)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 658, in on_hard_timeout
    raise TimeLimitExceeded(job._timeout)
TimeLimitExceeded: TimeLimitExceeded(300.0,)
[2020-03-26 13:46:09,271: ERROR/MainProcess] Hard time limit (300.0s) exceeded for apps.geoprocessing_api
.tasks.analyze_catchment_water_quality[99bec67c-0056-44a6-8a33-bf45746a91d5]
[2020-03-26 13:46:09,272: ERROR/MainProcess] Task 99bec67c-0056-44a6-8a33-bf45746a91d5 run from job 27439
26 raised exception: TimeLimitExceeded(300.0,)
None
[2020-03-26 13:46:09,475: ERROR/MainProcess] Process 'ForkPoolWorker-1' pid:2339 exited with 'signal 9 (S
IGKILL)'
[2020-03-30 12:48:12,495: WARNING/MainProcess] Restoring 4 unacknowledged message(s)
[2020-03-30 12:48:24,008: INFO/MainProcess] Connected to redis://cache.service.mmw.internal:6379/2
[2020-03-30 12:48:24,022: INFO/MainProcess] mingle: searching for neighbors
[2020-03-30 12:48:25,058: INFO/MainProcess] mingle: all alone
```
```
[2020-03-26 13:35:40,939: INFO/MainProcess] Received task: apps.geoprocessing_api.tasks.analyze_nlcd[9143
7c0d-4c3f-4a56-80c3-381a745cee7b]
[2020-03-26 13:35:41,658: INFO/MainProcess] Received task: apps.core.tasks.save_job_result[4369ccba-5ff3-
46ff-a98e-3bee91e5f7c5]
[2020-03-26 13:35:54,609: WARNING/ForkPoolWorker-1] GEOS_NOTICE: Self-intersection at or near point 17955
15.0000000012 2076375.0000000005
[2020-03-26 13:40:16,476: ERROR/MainProcess] Task ef6cce02-88a8-4e67-8495-9178cb5ddb92 run from job 27438
59 raised exception: TimeLimitExceeded(300.0,)
None
[2020-03-26 13:40:16,614: ERROR/MainProcess] Task handler raised error: TimeLimitExceeded(300.0,)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 658, in on_hard_timeout
    raise TimeLimitExceeded(job._timeout)
TimeLimitExceeded: TimeLimitExceeded(300.0,)
[2020-03-26 13:40:16,615: ERROR/MainProcess] Hard time limit (300.0s) exceeded for apps.geoprocessing_api
.tasks.analyze_catchment_water_quality[ef6cce02-88a8-4e67-8495-9178cb5ddb92]
[2020-03-26 13:40:16,617: ERROR/MainProcess] Task ef6cce02-88a8-4e67-8495-9178cb5ddb92 run from job 27438
59 raised exception: TimeLimitExceeded(300.0,)
None
[2020-03-26 13:40:16,822: ERROR/MainProcess] Process 'ForkPoolWorker-1' pid:2340 exited with 'signal 9 (S
IGKILL)'
[2020-03-30 12:48:12,496: WARNING/MainProcess] Restoring 4 unacknowledged message(s)
[2020-03-30 12:48:24,580: INFO/MainProcess] Connected to redis://cache.service.mmw.internal:6379/2
[2020-03-30 12:48:24,592: INFO/MainProcess] mingle: searching for neighbors
[2020-03-30 12:48:25,695: INFO/MainProcess] mingle: sync with 1 nodes
[2020-03-30 12:48:25,696: INFO/MainProcess] mingle: sync complete
```

In all these cases, we see the same pattern: a `GEOS_NOTICE` warning, then a timeout on `analyze_catchment_water_quality`, then the worker dying.

Anecdotally, the self-intersection warning most commonly happens for RWD shapes.

Figure out what is this edge case, and handle it in a manner that doesn't lead to the worker dying.

**Comment by rajadain** [comment]
These coordinates [translate to the center of the globe](https://epsg.io/map#srs=3857&x=1795514.999593&y=2076375.000067&z=2&layer=streets):

![image](https://user-images.githubusercontent.com/1430060/81599534-9d338c00-9396-11ea-820a-6633ad3b6e6d.png)

So there is likely some other mistake happening further up the chain causing this.

**Comment by rajadain** [comment]
These are being seen again recently. Will do greater investigation if frequency increases.

**Comment by rajadain** [comment]
I downloaded last year's worth of logs from Papertrail and grepped for SIGKILL, resulting in this file: [sigkill_only.txt](https://github.com/user-attachments/files/19799543/sigkill_only.txt)

Counting the [number of occurrences per day](https://docs.google.com/spreadsheets/d/195CK5TaxsqVTE6xV--58lAHyYiCfMaa_PKAwulCCDXw/), we do see an uptick in recent weeks:

<img width="978" alt="Image" src="https://github.com/user-attachments/assets/337f60de-19f7-4702-895a-508d47bb71f1" />

I will keep an eye on this, and add to it as we encounter more messages.

**Comment by rajadain** [comment]
Latest chart as of today, with 0 incident days marked as such for more accurate visualization:

<img width="1151" height="380" alt="Image" src="https://github.com/user-attachments/assets/838637a6-a0df-4337-8948-ca8043b79851" />
