### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3353]
View details in Rollbar: [https://rollbar.com/WikiWatershed/ModelMyWatershed/items/98/](https://rollbar.com/WikiWatershed/ModelMyWatershed/items/98/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/opt/app/apps/modeling/views.py", line 253, in scenario_custom_weather_data
    scenario.weather_custom)
  File "/opt/app/apps/modeling/calcs.py", line 51, in get_weather_modifications
    .format(','.join(rows[0]), 1))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)
```

**Comment by rajadain** [comment]
his is the related file: https://s3.console.aws.amazon.com/s3/object/mmw-production-data-us-east-1/p31710/s54517/weather_data_sample.csv?region=us-east-1&tab=overview. Seems like someone just uploaded the sample that comes with the app. Strange that it should not work. Downloaded the file, can’t find anything wrong with it. May be an encoding / line ending issue.

**Comment by rajadain** [comment]
This has now occurred more than 10 times.
