### ISSUE TITLE
Boundary Search Broken post Django Upgrade

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3447]
https://rollbar.com/WikiWatershed/ModelMyWatershed/items/179/

```
Internal Server Error: /mmw/modeling/boundary-layers-search/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/opt/app/apps/modeling/views.py", line 702, in boundary_layer_search
    result = boundary_search_context(search_term)
  File "/opt/app/apps/modeling/calcs.py", line 396, in boundary_search_context
    _do_boundary_search(search_term)
  File "/opt/app/apps/modeling/calcs.py", line 458, in _do_boundary_search
    point = wkb_r.read(row[4])
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/gis/geos/io.py", line 18, in read
    return GEOSGeometry(super().read(wkb))
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/gis/geos/prototypes/io.py", line 153, in read
    return wkb_reader_read_hex(self.ptr, wkb, len(wkb))
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/gis/geos/libgeos.py", line 152, in __call__
    return self.func(*args)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/gis/geos/prototypes/threadsafe.py", line 47, in __call__
    return self.cfunc(self.thread_context.handle.ptr, *args)
ctypes.ArgumentError: argument 3: <class 'TypeError'>: wrong type
```

**Comment by rajadain** [comment]
Shares points with #3446
