### ISSUE TITLE
Increase HTTP Max Content Length of Geoprocessing Service

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3478]
We're seeing errors like this:

```
Feb 03 21:16:26 ip-10-0-1-142 geoprocessing[479]: [ERROR] [02/03/2022 21:16:26.192] [WebServer-akka.actor.default-dispatcher-6171] [akka://WebServer/user/StreamSupervisor-0/flow-4323-0-unknown-operation] Error during preStart in [akka.http.scaladsl.model.HttpEntity$Limitable@321f922d]
Feb 03 21:16:26 ip-10-0-1-142 geoprocessing[479]: EntityStreamSizeException: actual entity size (Some(85990207)) exceeded content length limit (52428800 bytes)! You can configure this by setting `akka.http.[server|client].parsing.max-content-length` or calling `HttpEntity.withSizeLimit` before materializing the dataBytes stream.
Feb 03 21:16:26 ip-10-0-1-142 geoprocessing[479]:         at akka.http.scaladsl.model.HttpEntity$Limitable$$anon$1.preStart(HttpEntity.scala:609)
Feb 03 21:16:26 ip-10-0-1-142 geoprocessing[479]:         at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:520)
Feb 03 21:16:26 ip-10-0-1-142 geoprocessing[479]:         at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:380)
Feb 03 21:16:26 ip-10-0-1-142 geoprocessing[479]:         at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:538)
Feb 03 21:16:26 ip-10-0-1-142 geoprocessing[479]:         at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:586)
Feb 03 21:16:26 ip-10-0-1-142 geoprocessing[479]:         at akka.actor.Actor$class.aroundPreStart(Actor.scala:510)
Feb 03 21:16:26 ip-10-0-1-142 geoprocessing[479]:         at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:529)
Feb 03 21:16:26 ip-10-0-1-142 geoprocessing[479]:         at akka.actor.ActorCell.create(ActorCell.scala:590)
Feb 03 21:16:26 ip-10-0-1-142 geoprocessing[479]:         at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
Feb 03 21:16:26 ip-10-0-1-142 geoprocessing[479]:         at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
Feb 03 21:16:26 ip-10-0-1-142 geoprocessing[479]:         at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
Feb 03 21:16:26 ip-10-0-1-142 geoprocessing[479]:         at akka.dispatch.Mailbox.run(Mailbox.scala:223)
Feb 03 21:16:26 ip-10-0-1-142 geoprocessing[479]:         at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
Feb 03 21:16:26 ip-10-0-1-142 geoprocessing[479]:         at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
Feb 03 21:16:26 ip-10-0-1-142 geoprocessing[479]:         at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
Feb 03 21:16:26 ip-10-0-1-142 geoprocessing[479]:         at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
Feb 03 21:16:26 ip-10-0-1-142 geoprocessing[479]:         at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

https://rollbar.com/WikiWatershed/ModelMyWatershed/items/210/?utm_campaign=exp_repeat_item_message&utm_medium=slack&utm_source=rollbar-notification
https://rollbar.com/WikiWatershed/ModelMyWatershed/items/225/?utm_campaign=new_item_message&utm_medium=slack&utm_source=rollbar-notification

**Comment by rajadain** [comment]
This can be reproduced as follows:

1. Run `vagrant ssh worker -c 'sudo journalctl -u mmw-geoprocessing.service -f'`
2. Analyze the Lower White HUC-8 in Indiana:
    ![image](https://user-images.githubusercontent.com/1430060/152826123-ab3fccb4-2c5b-4064-bb30-64747cc4f712.png)
3. Observe the output of the log from Step 1 and see the failure
