### ISSUE TITLE
Subbasin Modeling Failing for some HUC-12s

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3602]
When running Subbasin Modeling for the Philadelphia Schuylkill HUC-12, we get the following error in Celery:

```
[2023-10-31 16:01:33,943: ERROR/ForkPoolWorker-2] Task 5e0bf758-35ef-422e-897a-6ae5bbbb36f0 run from job 218 raised exception: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app/apps/modeling/tasks.py", line 439, in run_srat
    result = format_subbasin(watersheds, srat_catchment_result, gmss)
  File "/opt/app/apps/modeling/tasks.py", line 230, in format_subbasin
    aggregate['HUC12s'] = {huc12_id: add_huc12(result, aggregate)
  File "/opt/app/apps/modeling/tasks.py", line 230, in <dictcomp>
    aggregate['HUC12s'] = {huc12_id: add_huc12(result, aggregate)
  File "/opt/app/apps/modeling/tasks.py", line 214, in add_huc12
    'Catchments': {
  File "/opt/app/apps/modeling/tasks.py", line 215, in <dictcomp>
    comid: format_catchment(result, catchment_loads_template)
  File "/opt/app/apps/modeling/tasks.py", line 137, in format_catchment
    load_type, load_source = key.split('_')
ValueError: too many values to unpack (expected 2)
```

This is because this line assumes there is only one underscore in the key:

https://github.com/WikiWatershed/model-my-watershed/blob/d1748c795ea31c95e5f63402a97b54a8ee5b7dda/src/mmw/apps/modeling/tasks.py#L131-L139

but in some cases, such as `tn_conc_ptsource`, there's more.

This can likely be fixed by looking for the last underscore and splitting there.

**Comment by rajadain** [comment]
Likely solvable by something like this:

```diff
diff --git a/src/mmw/apps/modeling/tasks.py b/src/mmw/apps/modeling/tasks.py
index 0f6db966..47c2bec4 100644
--- a/src/mmw/apps/modeling/tasks.py
+++ b/src/mmw/apps/modeling/tasks.py
@@ -132,8 +132,11 @@ def format_subbasin(huc12_gwlfe_results, srat_catchment_results, gmss):
             # A sample load source key is 'tnload_hp'.
             # The first half 'tnload' indicates which kinds of loads
             # The second half 'hp' is the acronym of the source of loads
-            if '_' in key:
-                load_type, load_source = key.split('_')
+            # Sometimes the first half has underscores, like 'tn_conc_ptsource'
+            split_at = key.rfind('_')
+            if split_at > -1:
+                load_type = key[0:split_at]
+                load_source = key[split_at:]
                 for load in loads_template:
                     if load_source == settings.SRAT_KEYS[load['Source']]:
                         add_load_by_key(load_type, value, load)
```
