### ISSUE TITLE
fix failing SuggestionModel unit test

### ISSUE THREAD

**Issue by lewfish** [WikiWatershed/model-my-watershed#530]
I get the following unit test failure about half of the time when running testem on the  develop branch.

SuggestionModel
#setMapViewLocation
sets map model's position attributes to the geocode result position ‣
TypeError: Cannot read property 'x' of undefined
    at Object.L.DomUtil.getTranslateString (http://localhost:7357/js/test.vendor.js:44453:22)
    at Object.L.DomUtil.setPosition (http://localhost:7357/js/test.vendor.js:44470:47)
    at L.PosAnimation.L.Class.extend.stop (http://localhost:7357/js/test.vendor.js:52038:13)
    at L.Map.include.setView (http://localhost:7357/js/test.vendor.js:52112:18)
    at Marionette.ItemView.extend.updateView (http://localhost:7357/js/test.bundle.js:3577:30)
    at triggerEvents (http://localhost:7357/js/test.vendor.js:21368:57)
    at Backbone.Events.trigger (http://localhost:7357/js/test.vendor.js:21308:19)
    at _.extend.set (http://localhost:7357/js/test.vendor.js:21528:16)
    at Backbone.Model.extend.setMapViewToLocation (http://localhost:7357/js/test.bundle.js:4895:17)
    at Context.<anonymous> (http://localhost:7357/js/test.bundle.js:5270:23)

**Comment by lewfish** [comment]
It seems like I'm the only one who gets this failure.

**Comment by lewfish** [comment]
The failure doesn't occur when running it in isolation from the other tests.
