### ISSUE TITLE
Exceptions related to missing model_input keys

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#623]
The following two tracebacks have been pulled from staging over the last 7 days:

```
Task apps.modeling.tasks.run_tr55[3299076d-6a57-48c8-b6b8-a6571eb0a3df] raised unexpected: KeyError(u'inputmod_hash',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "apps/modeling/tasks.py", line 197, in run_tr55
    'inputmod_hash': model_input['inputmod_hash'],
KeyError: u'inputmod_hash'
```

```
Internal Server Error: /api/modeling/start/tr55/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/opt/app/apps/modeling/views.py", line 202, in start_tr55
    task_list = _initiate_tr55_job_chain(model_input, job.id)
  File "/opt/app/apps/modeling/views.py", line 213, in _initiate_tr55_job_chain
    job_chain = _construct_tr55_job_chain(model_input, job_id)
  File "/opt/app/apps/modeling/views.py", line 221, in _construct_tr55_job_chain
    current_hash = model_input['modification_hash']
KeyError: u'modification_hash'
```

**Comment by mmcfarland** [comment]
I believe this was due to stale data for old projects, which have been pruned.    These exceptions aren't found in the last 30 days of staging logs.
