### ISSUE TITLE
Error when using County Lines as boundary selection

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#884]
The app will `500` when trying to use the County Line boundary for an AoI selection:

```
GEOSException: Error encountered checking Geometry returned from GEOS C function "GEOSWKBReader_readHEX_r".
```

**Comment by mmcfarland** [comment]
```python
Internal Server Error: /api/modeling/boundary-layers/county/245/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/opt/app/apps/modeling/views.py", line 252, in boundary_layer_detail
    geojson = json.loads(GEOSGeometry(row[0]).geojson)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/gis/geos/geometry.py", line 62, in __init__
    g = wkb_r().read(force_bytes(geo_input))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/gis/geos/prototypes/io.py", line 172, in read
    return wkb_reader_read_hex(self.ptr, wkb, len(wkb))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/gis/geos/prototypes/threadsafe.py", line 56, in __call__
    return self.cfunc(self.thread_context.handle.ptr, *args)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/gis/geos/prototypes/errcheck.py", line 33, in check_geom
    raise GEOSException('Error encountered checking Geometry returned from GEOS C function "%s".' % func.__name__)
```

**Comment by jamesmcclain** [comment]
Review instructions:

**To Test**
   * Download the new county file from `smb://fileshare/users/jmcclain/boundary_county.sql.gz`
   * Copy the file to the app VM: `ssh boundary_count.sql.gz vagrant@33.33.34.20:`
   * SSH into the app VM: `vagrant ssh worker`
   * Setup environment variables:
```shell
export PGHOST=$(cat /etc/mmw.d/env/MMW_DB_HOST)
export PGDATABASE=$(cat /etc/mmw.d/env/MMW_DB_NAME)
export PGUSER=$(cat /etc/mmw.d/env/MMW_DB_USER)
export PGPASSWORD=$(cat /etc/mmw.d/env/MMW_DB_PASSWORD)
```
   * Update the table: `zcat boundary_county.sql.gz | psql --single-transaction`
   * Now try enabling the county boundaries from the "Select By Boundary" menu.  Should be able to successfully select them, whereas there as an error before.

**Comment by lliss** [comment]
+1. Nicely done. Tested.
