### ISSUE TITLE
Omitting layer table name produces exception

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#899]
```
Internal Server Error: /api/modeling/boundary-layers/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/opt/app/apps/modeling/views.py", line 241, in boundary_layer_detail
    table_name = layers[0]['table_name']
KeyError: u'table_name'
```

**Comment by mmcfarland** [comment]
I'm not sure how these invalid requests are getting generated, I wondered about a crawlerbot but it looks like it's from an Android tablet:

`Mozilla/5.0 (Linux; Android 5.1.1; Nexus 7 Build/LMY48I) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.94 Safari/537.36`

We should try our Nexus 7 to see if it's building the layers dropdown incorrectly, and either way, guard against this key error producing a 500 and return a 400 Bad Request or similar.
