### ISSUE TITLE
ITSI Signup field length errors

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#974]
The production site is reporting unhandled errors relating to ITSI user sign up requests with a too long field name.

```
Internal Server Error: /user/itsi/authenticate
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/app/apps/user/views.py", line 132, in itsi_auth
    return itsi_create_user(request, itsi_user)
  File "/opt/app/apps/user/views.py", line 155, in itsi_create_user
    last_name=last_name,
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/models.py", line 187, in create_user
    **extra_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/models.py", line 182, in _create_user
    user.save(using=self._db)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
DataError: value too long for type character varying(30)
```

**Comment by mmcfarland** [comment]
It's unclear which field is generating this problem, but some stats from production indicate username is the likeliest culprit.  The long-ish usernames are all email addresses with an `.itsi` appended to it.

```sql
modelmywatershed=> select length(username) from auth_user order by length(username) desc limit 10;
 length 
--------
     30
     26
     24
     24
     23
     23
     21
     21
     20
     17
```

```sql
modelmywatershed=> select length(first_name) from auth_user order by length(first_name) desc limit 10;
 length 
--------
     13
      9
      9
      9
      9
      9
      9
      9
      9
      8
```

```sql
modelmywatershed=> select length(last_name) from auth_user order by length(last_name) desc limit 10;
 length 
--------
     16
     16
     15
     14
     13
     13
     11
     11
     11
     10
```

**Comment by mmcfarland** [comment]
There's [been some lively debate](https://code.djangoproject.com/ticket/20846) on increasing the default `auth.User` model username field from 30 to something more accommodating, but the preferred solution seems to be a Custom User model.  However, since we didn't start the project with one, it would involve a fair amount of moderately risky [code changes and data migrations](https://www.caktusgroup.com/blog/2013/08/07/migrating-custom-user-model-django/) on the current user table.  Since this is only happening on auto-ITSI signups, I'm going to try to just keep the largely obscured generated username unique and under 31 chars.
