### ISSUE TITLE
`run_tr55` doesn't handle key errors

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#976]
I'm not sure if this was an old project that has an invalid key, but I believe `developed_high` is (supposed to be) a valid land type.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "apps/modeling/tasks.py", line 194, in run_tr55
    model_output = simulate_day(aoi_census, precip, cell_res=resolution)
  File "/usr/local/lib/python2.7/dist-packages/tr55/model.py", line 395, in simulate_day
    return simulate_modifications(census, fn, cell_res, precolumbian)
  File "/usr/local/lib/python2.7/dist-packages/tr55/model.py", line 343, in simulate_modifications
    mod = create_modified_census(census)
  File "/usr/local/lib/python2.7/dist-packages/tr55/model.py", line 228, in create_modified_census
    parent = mod['distribution'][cell]
KeyError: u'a:developed_high'
```

**Comment by jamesmcclain** [comment]
The code where the exception originated (`tr55/model.py:228`) does not exist in newer version of the code.
