### ISSUE TITLE
Unable to start geoprocessing service

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#996]
I'm unable to start the geoprocessing service after freshly provisioning the app and worker VMs. Here is an error from the application logs when I try to analyze a 1km^2 region.

```
Internal Server Error: /api/modeling/start/analyze/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/opt/app/apps/modeling/views.py", line 167, in start_analyze
    task_list = _initiate_analyze_job_chain(area_of_interest, job.id)
  File "/opt/app/apps/modeling/views.py", line 215, in _initiate_analyze_job_chain
    routing_key = choose_worker()
  File "/opt/app/apps/modeling/views.py", line 209, in choose_worker
    celery.current_app.control.inspect().ping().keys())
AttributeError: 'NoneType' object has no attribute 'keys'
```

**Comment by jamesmcclain** [comment]
This means that the worker selection function is getting back an empty list of available workers.

**Comment by kdeloach** [comment]
Starting the celeryd service fixed this. Thanks.

**Comment by jamesmcclain** [comment]
You are welcome.  It is curious that it did not start on its own, but I am glad it is working.
